### ISSUE TITLE
Image asset uploaded from computer not rendering on staging site

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#190]
I tried to upload an image (a png file, available here: https://docs.google.com/file/d/0B82exFJJWyJqbEI3NGpPTnRudzA/edit) as both an image and map asset.

After I clicked "save changes," the image went through the upload process (and reached "100% Upload"), and then did not render. Here's a screen shot: https://docs.google.com/file/d/0B82exFJJWyJqTmlIbzhzOFBlUlE/edit

When I clicked "Edit," the image information was not retained. Screenshot: https://docs.google.com/file/d/0B82exFJJWyJqOVJjUU0zUXpuV0U/edit

It also did not show up in the preview.

The only edit I made to the story before trying to upload an image was changing the title. I saw the same behavior when I tried to upload the file as a map asset.

It seems to be working fine on the test site.

**Comment by ghing** [comment]
I was able to replicate this issue and verify that the file is being uploaded properly.

It is not being displayed because Django is returning a 404 error when trying to access the uploaded image.  It appears that Django is returning a bit of a strange URL for the image ("NetworkError: 404 NOT FOUND - http://staging.denverchildrenscorridor.org/media/filer/2012/08/28/screen_shot_2012-08-28_at_92508_am_4.png/") in that it ends in a /

The image information will never be retained in edit because the server doesn't know the local path (on your computer) of the file that was uploaded.

**Comment by ghing** [comment]
This is because of my recent change of setting DEBUG=False in the settings module on staging. The logic needed to serve the image files in urls.py gets turned off when DEBUG=False.  I need to revisit this to figure out the best way to configure this.  Bit, for now, image upload works on staging again.

**Comment by ghing** [comment]
I fixed this by configuring nginx to serve the media files as well as the static files.  The relevant configuration looks like this:

```
location /media {
        alias               /srv/www/atlas_staging/atlas/media;
}
```
