### ISSUE TITLE
YouTube video embed not rendering on staging site

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#191]
While creating a story with the builder, I embedded a YouTube video that didn't render.

Here is what I did before adding the video:
- created a new story with the explainer template
- edited the first couple of slides
- changed the "Element 1" slide from a 1-up to a 2-up layout
- added text
- added a video using this YouTube link: http://youtu.be/qbjhy-G44EY (accessed via the "Share" button on YouTube)

After doing so, the video didn't render, and it looked like this:
https://docs.google.com/file/d/0B82exFJJWyJqU0xkVjlnbXhGcnM/edit

When I clicked "Edit," the link was retained in the URL field.

The video didn't show up in the video, the preview, or on the site once the story was published.

**Comment by ghing** [comment]
The issue is that the new short-style YouTube URLs don't match the regular expression that django-oembed uses for YouTube out of the box.  Luckily, this is easily configurable.  I did a quick and dirty fix that added a new "provider" with a regular expression that matches the shortened YouTube URLs.  @jwirfs-brock, can you check whether or not this works?

The long term fix is to make a post_syncdb hook that adds a provider with a regexp for the shortened URLs.

**Comment by jwirfs-brock** [comment]
Thanks, Geoff. I'll try it this morning. I also noticed that if you use the
full YouTube URL, it works but the video is really large (doesn't resize to
the asset box). I'll take a screenshot and log a new issue for that when I
get in to the office.

**Comment by jwirfs-brock** [comment]
@ghing The embed is working, but the video isn't re-sizing. Is there a way to resize via oembed, or do I have to grab the embed code, which uses an ifram?

<iframe width="560" height="315" src="http://www.youtube.com/embed/wJP-RUrNBCs" frameborder="0" allowfullscreen></iframe>

**Comment by ghing** [comment]
@jwirfs-brock Re: resizing, I'll respond to this over at #211 because that seems like the relevant issue for that particular aspect.
