### ISSUE TITLE
After deleting a section that is part of a template, it doesn't disapear from the nav at the bottom of the Story Builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#210]
In the Story Builder, when I delete a template section (i.e., "Image and Text" section in PhotoVoice template, "Element 1" in Explainer template) -- by clicking on the blue "x" in the top right of that section as it appears in the bottom nav -- I'm getting the dialog box that says, "Are you sure you want to delete this section?" However, the deleted section remains in the bottom nav (does not disappear).

It seems that the section is in fact getting deleted, because when you preview the story, it doesn't show up.

This problem isn't happening for user-created sections. (I.e., if I create a new section and then delete it, it disappears from the bottom nav.)

Here's an annotated picture of what is happening:

![Section deletion bug screenshot](http://i.imgur.com/c7GdI.png)

(screenshot originally posted at https://docs.google.com/file/d/0B82exFJJWyJqb2hTWm45NGQ5Y0k/edit)

**Comment by ghing** [comment]
I was able to replicate this issue.  The error that's being thrown when trying to delete the section is:

TypeError: view is undefined
http://127.0.0.1:8000/static/js/builder/views.js
Line 1275

**Comment by ghing** [comment]
Debugging note: this error is only seen when trying to remove a template section when editing a story for the first time.  If you create a story, visit another page and return to the builder or reload the builder page, and then remove the template section, the error is not seen.

**Comment by ghing** [comment]
The issue is that when the story is loaded from the template, the thumbnail view for the new section is being added to this._thumbnailViews with a key of undefined because the section model does not yet have an id (because it hasn't been saved).

The offending line of code is in SectionListView.addSectionThumbnail (views.js, line 1193).

The solution is, I think to use the section model's cid when adding the thumbnail.  The remaining question is whether to update the keys to the actual id from the server when the story is saved initially, or to just modify the getThumbnailView to also fetch by cid.
