### ISSUE TITLE
When embedding a video with full YouTube URL, the video isn't resizing (is appearing in large format)

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#211]
In the story builder, I uploaded a video asset using the following URL: http://www.youtube.com/watch?v=SSQQyPsVAvU&feature=plcp

This isn't the "share" URL, but just the URL that appears in the browser when you are viewing the video on YouTube.

In the builder, the video is appearing in a large size/isn't resizing to the smaller asset box when using the side-by-side layout. However, when I put the video in the 1-Up layout, the video does appear to resize to get larger.

Here are some screen shots...

Side-by-side:
https://docs.google.com/file/d/0B82exFJJWyJqRkhDZVpXNFIxbHc/edit

1-Up:
https://docs.google.com/file/d/0B82exFJJWyJqV1p6bWE2QVJzZTA/edit

**Comment by ghing** [comment]
@jwirfs-brock Both the manual embed and the oembed response uses an iframe.  The problem is that in both cases the iframe specifies a specific width.

There are a couple of things we can do to address this:

1) See if we can define a CSS rule with an "!important" directive that makes the iframe width be a certain size.

2) Tell the oEmbed endpoint to restrict the size of the returned iframe.  oEmbed supports a max_size argument that will limit the size of the returned iframe.  In this scenario we'd have to decide on the width we'd want things to be or provide some way for the user to specify the size they want. 

I'll look into this.

**Comment by ghing** [comment]
This is affected a bit by the switch from djangoembed to micawber (#226, 8d9e467660fab3d46bcf0cb8189eb700a85c485e).  Prior to that there was a max_width parameter of 1000 being passed to the different oEmbed endpoints in order to work around an issue with Flickr's oEmbed implementation.  It appears that either the switch to micawber or an update on Flickr's end made this unnecessary.  Now, the iframe gets a width of 480px, the default embed size returned by the oEmbed endpoint regardless of whether it is shown in the side by side or 1-up layouts.

It now looks less crazy, but still gets cut off a bit by.  I'm going to investigate whether I can make it fit better with CSS.
