### ISSUE TITLE
It is unclear that in the Story Builder you can edit a Section title

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#216]
Within the story builder, when you create a new section or are working on a templated section, it isn't evident that the titles are editable. We need some kind of graphic styling so it's clear that you can edit a title.

Here's a screenshot:
https://docs.google.com/file/d/0B82exFJJWyJqMG5KR3lmaVZPSGs/edit

**Comment by bpawlak** [comment]
Yes, I mentioned that one a while back... I think we can do two things:  1) provide a subtle outline to all editable elements on the page and 2) when a user hovers over an editable element, the border color changes to indicate that the user can interact with it.  In the wireframes for the builder, I originally had a grey background and border around edited elements with helper text such as "Title (click here to add your title)" and when the user clicked into that area, it would look like a standard form element.  Once done, the user would have learned how that works, so that s/he could then click on the title again to edit.  But the hover effect may provide some additional queues to that end.

**Comment by ghing** [comment]
@bpawlak I think that makes sense.  I'll take that approach to addressing this issue.

**Comment by jwirfs-brock** [comment]
@ghing @bpawlak 

I like Bill's suggestions a lot. Let's go for the subtle outline and the hover color change.

Also, instead of displaying "New Section" let's display "Click here to edit your section heading" (similar to how the title is displayed Story Information section).

Also, if someone doesn't edit the section title for a new section, can we have it not display, rather than have it display the unedited title?

**Comment by ghing** [comment]
@jwirfs-brock I broke out your requests for changing the placeholder for the section title and the hiding of the new section title as a separate issue (#243) since this functionality's implementation is pretty separate from the highlighting.
