### ISSUE TITLE
Heading tags/styles seem off in templates

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#253]
The top-level headings (the one that wraps body_title) in the two-column template (twocol.html) are an h3, but there don't seem to be any h1 or h2 tags for it to nest under.  Is h1 being used for the logo?  Is there some other element on every page that is an h2?

Also, the h2 tags seem really, really huge.  I'm guessing this is for the homepage.  Maybe we can have more sane font sizes for the defaults and a special class on the body to make those h2s big.

E.g.

In base.html:

```
<body class="{% block body_class %}{%endblock %}"
```

In homepage.html:

```
{% block body_class %}homepage{%endblock %}
```

```
In style-new.css:
.h2 {
  font-size: /* something sane */;
}
.homepage h2 {
  font-size: /* real big now */;
}
```

**Comment by ghing** [comment]
in my opinion, all the h3s on the home page should also be h2s, but just styled differently right now, only the big thing at the top is an h2 I think that each section is at the same level in terms of the document, so they should be h2 and that top-level one ("Tell Your Story. Transform Community") should just be an h2 with a special class to make it bigger then the page title in the twocol.html should be wrapped in an h2, not an h3.

**Comment by patternleaf** [comment]
yup, there don't seem to be h1s used anywhere in the html burger templates. maybe they did intend for the logo to use h1. is your preference to use h1 as page titles, as opposed to the logo? or both, perhaps?

> in my opinion, all the h3s on the home page should also be h2s

i'd say the h2s in the top carousel are semantically weird to begin with. they're h2s for very small bits of text within list items; whereas the h3s in the doc are as you say: more sensibly h2s. not sure of a better route for those carousel h2s, though.

my hit is the html burger code was basing hx tags on style rather than semantics. i hadn't attempted to clean them up in any way and probably made the situation worse at some point—will try to clean it up now.

**Comment by patternleaf** [comment]
following conversation with @ghing, we're going with h1s as page title, and h2s for top-level content below that, etc. the logo will be an image, per suggestions at http://csswizardry.com/2010/10/your-logo-is-an-image-not-a-h1/.

i'll make a pass through the template code to update to this standard.

**Comment by patternleaf** [comment]
ok, i've updated the following templates:
- homepage
- twocol (about page, generic content)
- story detail
- project detail
- explore page

with h1s as page title, and adjusted other headers and styles accordingly. i did make an exception on the homepage, wherein i added an h1 next to the logo, display:none. 

it's quite likely i've missed areas with which i'm unfamiliar in the site, and those areas may need more work.

**Comment by patternleaf** [comment]
i'm going to close this for now. it sounds like the main areas i didn't specifically address are liable to change style-wise anyway. let's make new issues for things as they come up.
