### ISSUE TITLE
"Add a Section" behavior in Story Builder happens too quickly, causing users to add new sections unintentionally

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#266]
Because the "Add a Section" mouse over is so sensitive and happens to quickly, users often inadvertently add a new section when they are trying to click on an existing section.

Is there a way we can make this less sensitive? It's confused just about everyone who has seen the builder.

**Comment by ghing** [comment]
@jwirfs-brock, @bpawlak also mentioned this over at #224 and I've run into this as well,  I'm going to close that issue and move the discussion to this issue.

**Comment by jwirfs-brock** [comment]
Great. I didn't realize this was already logged as an issue. Thanks for
merging.

**Comment by ghing** [comment]
Here are some options:
- Always show a less obtrusive icon (maybe just a "+") between sections.  This would mean that things aren't showing and hiding themselves as much and reveals the functionality right away.

These options can all be mixed together:
- Change the icon that appears when the user hovers in the space between the sections so that it looks different from the sections around it.
- Require a confirmation before the new section is added.  That way a new section isn't created right away for accidental clicks.
- Don't make the whole revealed element the link that triggers the new section creation.  Instead make it a link inside the revealed element, so the user will have to move their mouse a little to actually create the new section.  
  @bpawlak suggested a version of this particular fix

![](http://i.imgur.com/s2khX.png)

original at https://docs.google.com/drawings/d/1PdlRth8WFHitHBjFK1zX9gYsKTsF6f_tjCVDIM6UNGY/edit

I can do this, but might like to try the simpler version first because I think it would be nice to continue to just rely on CSS hover behavior instead of having to script another element popping up and fading out.  It might be possible to fake it by just pulling the element upwards with CSS.  I'll have to play around with this.

**Comment by bpawlak** [comment]
The small icon (+) between the sections that the user has to click on would definitely reduce the visual confusion.  If we can then assign a tooltip to the icon, we can get close to the interaction I originally came up with in the wireframes...

**Comment by ghing** [comment]
@bpawlak Should the small "+" icon always be there, or just when the space is hovered over?

**Comment by bpawlak** [comment]
I would say just when the space is hovered over, otherwise, you'd have the + icon inbetween each and every section at the bottom...

**Comment by jwirfs-brock** [comment]
So a user would have to hover over the space, then hover over the "+" to
see what it would actually do (add a new section) via the tool tip? I guess
I'm having trouble visualizing that. I kind of like having the "+" always
there, otherwise users might not even know that they have the option of
adding a section. (Unless they pay attention carefully to the tour, of
course.)

**Comment by ghing** [comment]
Ok, so what I'm hearing is:
- When the user mouses over the space, a  "+" icon is shown, but within a larger container, so the user has to move their mouse a bit to click it. 
- Hovering over the "+" icon will show a tooltip so the user knows that "+" means add a section

@jwirfs-brock I don't like crowding the interface with the pluses, but if I implement what I described above, it would be easy to just always show the pluses if the hiding doesn't improve things.

**Comment by bpawlak** [comment]
No, I'd say when you hover over the space, the two adjoining sections slide over a bit to reveal the (+) icon and the tooltip.  If the + is always shown, otherwise, you'd have an icon inbetween each and every section at the bottom...

**Comment by jwirfs-brock** [comment]
Ok, I think I understand now. Bill's suggestion sounds good.
