### ISSUE TITLE
Tour is shown every time the browser is reopened

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#297]
Right now the cookie expires each time the browser is closed, so when the user reopens the browser, they will see the tour.

**Comment by ghing** [comment]
@jwirfs-brock Can you confirm that the tour text and behavior is correct so I can make the tour disappear for longer periods (right now the cookie that hides the tour expires every time the browser is closed).  Assign this issue back to me if the tour text/behavior needs revision or if it's good to go.

**Comment by jwirfs-brock** [comment]
A few minor changes:
1. On the first tour item, "Building a story takes five simple steps," let's make this an ordered list instead of a bulleted list (now that Geoff Thomas's updated design has numbers next to the steps).
2. On the first tour item, "Publish/share" has a line break before "- Post your story..." -- this line break should be removed.
3. The three tour items describing the table of contents/section bar are placed on top of the bar, obscuring it. Can we have them placed right below the bar, with the arrows pointing up at the bar?
4. The final step, "Need even more tips?", needs a "Previous" button.
