### ISSUE TITLE
Body base font-size on landing page

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#308]
Viewing in Firefox 15.0.1, the body.base-template #main .text p font-size should be 12px but it's rendering much smaller than that. It's very difficult to read on a laptop screen.

Line 67 in CSS appears to be overwritten by line 792, per Firebug.

**Comment by wendynorris** [comment]
Same problem in story preview page. Font is too small.

**Comment by patternleaf** [comment]
ok, this is now updated on dev. part of the issue is that Times New Roman renders visually smaller at 12px than Georgia, which had been the default serif font. when i switched it over to Times New Roman at some point, the font size wasn't updated. 

right now on dev we're using Times New Roman 14px. looks pretty legible to my eyes.

also some general cleanup has happened, so the default body sans-serif font is gone. @tekhneco, can you review and close or comment? thanks.

**Comment by wendynorris** [comment]
Looks great. Will close issue.
