### ISSUE TITLE
Story preview page

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#311]
Odd and inconsistent line breaks on all the stories in preview mode _except_ Jordan's. Are contributors inadvertently adding hard returns in the body copy or carrying over Word code that's causing line breaks?

Example: http://staging.floodlightproject.org/stories/en-route/

A freshman writing seminar is being
offered at Regis University this year by the name of Writing for Social
Justice.  This class places students in the field, and connects them to
the community through direct service opportunities. The class also meets to discuss
their experiences and dissect larger issues of privilege and responsibility.

**Comment by patternleaf** [comment]
> Are contributors inadvertently adding hard returns in the body copy or carrying over Word code that's causing line breaks?

yeah—that seems likely; there are &lt;br> tags in there. there's no template/display-related code that would cause this.

**Comment by wendynorris** [comment]
Okay, I'll make a note to go in and edit those out.

**Comment by wendynorris** [comment]
List of stories with odd line breaks: 

http://staging.floodlightproject.org/stories/camoplauge/
http://staging.floodlightproject.org/stories/school-funding-an-overview-from-ednews-colorado/
http://staging.floodlightproject.org/stories/en-route/
http://staging.floodlightproject.org/stories/school-vouchers-an-overview-from-ednews-colorado/
http://staging.floodlightproject.org/stories/school-testing-an-overview-from-ednews-colorado/
http://staging.floodlightproject.org/stories/turning-the-tables-at-hinkley-high-school/
http://staging.floodlightproject.org/stories/the-grid-empowerment-and-soccer/
http://staging.floodlightproject.org/stories/what-is-fastracks/
http://staging.floodlightproject.org/stories/why-we-tell-stories-reflecting-on-july-22-2012/
http://staging.floodlightproject.org/stories/what-bus-stops-can-tell-us/
http://staging.floodlightproject.org/stories/pictures-for-translation/

Generally, the summary grafs look okay in the explorer page. The inserted <br> tags are evident in the story summary page. 

Here's an example from the Camoplauge [sic] story per Firebug: 

<section class="summary">

<p></p>

<p>
On September 1, 2012, an army of
<br>
community volunteers helped in the clean-up and assembly of the new Holly Peace
<br>
Park. This park is a physical sign of a community’s rebirth following the arson
<br>
of 2008.
</p>

<p></p>

</section>
<a id="launch-story-viewer" class="button" href="/en/stories/camoplauge/viewer/">View Story</a>
</section>

**Comment by ghing** [comment]
For most of these, the underlying issue is that the template for the story detail page automatically converts linebreaks in the text ('\r', '\n') to HTML breaks ('<br />').  I _think_ this is the behavior that we want because I think most people think hitting return/enter twice means a new paragraph, not highlighting it and selecting something in the editor.  It's a one line fix to turn this off if we find that users are creating tons of poorly formatted summaries.  For the most part it looks like a bit of sloppy copying and pasting was to blame for the linebreaks in weird places in the inputted summary text.

For stories with weird formatting, I removed the newlines.  For other stories in the list, the story text was formatted correctly and any weirdness is just how the browser breaks the lines at word breaks.  It just looks weird in some cases.
