### ISSUE TITLE
Make layout selection graphic

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#341]

**Comment by jwirfs-brock** [comment]
It's not necessarily blocking launch to have the layout selection not be graphic, but we do need to have it. On dev, it looks like it isn't there. Did we figure out the placement based on the email thread? I'm pasting that discussion here (minus the images):

@bpawlak said:
Current view – the layout chooser takes up as much space (with padding) as the Workflow steps…
Option 1: simply place it up in the section browser bar:
Option 2: shrink it in size (leave it where it is) and add a label to the drop down: "Layout Template?"
Option 3: move and shrink:
Option 4: Potentially integrate it into the active section thumbnail.  May need to change the position of the section thumbnail text:

 @ghing said:
One consideration is that moving it to the active section thumbnail or into the section list bar will take a non-trivial amount of coding since those are separate views that currently have access to different information.

I said:

I think it needs to have some kind of label. Without that, as a first time user you don't know what it is.

My preference is for Option 3 (shrinking it and having it in the section nav).

Based on the amount of coding it would take, my next preference would then be Option 2.

**Comment by bpawlak** [comment]
For launch I think it could simply have text that describes the layouts (side-by-side, 1-up, 3-up, etc.).  Switching between them is pretty quick.  The graphics are nice, but I wouldn't say it's anywhere near blocking

**Comment by jwirfs-brock** [comment]
I guess I goofed -- the graphics are implemented on dev, right? But the
issue is they are appearing below the section nav bar, and taking up space.
@bpawlak, is the placement of the layout selector a blocking issue for you?

**Comment by bpawlak** [comment]
nope. Just a bit of wasted vertical space and looks like it could be refined.  But not a blocker (it works!)

**Comment by patternleaf** [comment]
closing this as it's no longer blocking launch. let's open any new issues as they arise.
