### ISSUE TITLE
Featured image error overwriting byline 

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#344]
Noticed this in two stories. Appears that the featured image is not rendering properly. A thumbnail error message then overwrites the byline. 

Examples: 

http://staging.floodlightproject.org/stories/why-we-tell-stories-reflecting-on-july-22-2012/

http://staging.floodlightproject.org/stories/what-is-fastracks/

Don't see anything unusual in Firebug so it appears to be a system-generated error.

**Comment by ghing** [comment]
@tekhneco That's not an error message.  That's just what's shown when there isn't a featured image available to show.  This situation should go away once we get a default image from Geoff T. I'll double check that these stories don't have an appropriate featured image and that this isn't a manifestation of some other error, but this visual issue will be easily corrected once we get the default image.

**Comment by wendynorris** [comment]
Sounds good. Those were the only two stories I came across without
displayed featured images.
**
_wendy norris http://about.me/wendynorris_
 ceo + founder :: tekhne media, inc
a digital information and media collective
720 281 9378 :: mobile

*\* http://about.me/wendynorris
*
*

**Comment by ghing** [comment]
@tekhneco, here's an update

Here's the deal with these stories.  They were both created by Jon Denzler from the Django admin rather than the builder, so some of the ways the data was stored were a little wonky.  I fixed these 
- http://staging.floodlightproject.org/stories/why-we-tell-stories-reflecting-on-july-22-2012/ - No image assets for this story, just a Google Map that was incorrectly assigned an 'image' type

http://staging.floodlightproject.org/stories/what-is-fastracks/ - Flickr-based image asset created as an HTML snippet instead of a URL to the flickr image.  I fixed this.

Since there isn't any fundamental bug tied to the behavior you saw, I'm closing this and opening another ticket (#346) for tracking the need for default images.
