### ISSUE TITLE
accounts/login page: need icons/styling for social media

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#347]
big pretty buttons. might be nice to split the page into two columns, too: one for social media, one for regular login.

**Comment by patternleaf** [comment]
added buttons using css and FontAwesome:

![social-login](https://f.cloud.github.com/assets/73439/13943/1c50bb50-4621-11e2-8a75-d6ec5e3c7f8c.png)

**Comment by patternleaf** [comment]
note to self: these also need to be implemented on the register page.

**Comment by patternleaf** [comment]
closing this.

**Comment by ghing** [comment]
Assigning to @jwirfs-brock for final review

**Comment by ghing** [comment]
I tested this in Internet Explorer 9 and it looks like `border-radius` and the gradient aren't compatible so that the gradient spills over the button edges.

![social_signup_buttons_ie9](https://f.cloud.github.com/assets/110420/35535/0bebd9ec-5216-11e2-9d18-bcfde48736f6.png)

As far as I can tell, the options appear to be:
- Don't show a gradient in IE
- Don't show rounded corners in IE
- Use an image for the gradient in IE

In any case, we should use modernizr to feature detect the HTML5 gradient property rather than doing browser detection.

To me, this doesn't seem like a blocking change for deployment, but we should fix it.

**Comment by jwirfs-brock** [comment]
Yup, I'm also seeing the buttons rendering correctly in Chrome and Firefox but not IE. I think that's fine for now, and we should deploy with:
- no gradient in IE
- no rounded corners in IE

**Comment by ghing** [comment]
To make this work in IE, should we go with rounded corners and no gradient,
gradient and no rounded corners, or rounded corners and an image-based
gradient? The first 2 options are equally easy, the third is a bit more
complex, but provides the most consistent option between browsers. My
personal preference is option 2, no gradient and rounded corners.

**Comment by jwirfs-brock** [comment]
Oops, I don't think the rest of my comment went through after I updated it. I suggested no gradient and no rounded corners, but I didn't realize we could do one of gradient or rounded corners, so you can disregard that.

I agree that option 2, no gradient and rounded corners, sounds good for IE.
