### ISSUE TITLE
Extra space at end of Call to Action in Story Viewer

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#366]
There's a lot of extra scrollable space after the Call to Action in the Story Viewer. This looks a bit strange, because you can scroll all the way down so that the Call to Action heading isn't visible anymore. 

See: http://staging.floodlightproject.org/stories/the-denver-scores-cup/ and http://staging.floodlightproject.org/stories/workshop-1-video-find-your-story-with-one-powerful/ -- or pretty much any story.

**Comment by ghing** [comment]
The behavior you're seeing is a result of the functionality that snaps the top of the section to the top of the viewport when using the next/previous buttons.  I have to add extra space, otherwise, that section can't scroll all the way to the top.  I might be able to make that a little more intelligently (like removing the extra space when the user starts scrolling)

**Comment by ghing** [comment]
Closing this since this workaround and it's motivation is no longer a part of the viewer since we changed the viewing to be one section at a time in #518.
