### ISSUE TITLE
Position of message bar needs to be moved in Story Builder

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#378]
The message bar (which displays, "This story has been saved" after an auto save and a message about the asset library after a section or asset has been deleted) needs a new position now that we've implemented the new Story Builder design.

@ghing suggested shortening the message (so it no longer covers the width of the entire screen) and putting it between the Floodlight logo and the Preview/Start Over/Exit menu. @bpawlak do you have any suggestions?

**Comment by bpawlak** [comment]
I'm not sure why we really need to move the confirmation bar.  I'd suggest we make it fade out more quickly, but I don't see a real need to move it or change it, size-wise.  What are the drivers for moving/resizing it?

**Comment by jwirfs-brock** [comment]
Right now, because we have more elements taking up vertical space at the
top, it's showing up on top of the menus, which is a bit strange.

**Comment by bpawlak** [comment]
Think of it like the old confirmation dialogs in HTML... it's simply there to provide some quick feedback (only we don't have to force people to cancel it).

If we _were_ to move it, I'd move it below the section navigation container so that it's closer to where the user is focusing their eyes (i.e., the content containers).  

Another option would be to implement something growl-like: functionn.blogspot.com/2012/05/toastr-jquery-plugin-for-gnomegrowl.html
