### ISSUE TITLE
Style template selection view

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#383]
Geoff T's treatment:

![Geoff T's treatment image](http://i.imgur.com/reJCd.jpg)

**Comment by jwirfs-brock** [comment]
Updating this issue to align with our user feeback conversations (see: https://docs.google.com/document/d/1eBYGQJJ9G0sWBQS2QNPYD1bP6fC3LxTQGIODfSYT-qw/edit).

Here's the relevant notes from that discussion:

Decision:
- put text description of templates into collapsible div (like on Help page)
- “Find out more” with chevron
- Show icon, template name, tagline, examples

**Comment by patternleaf** [comment]
@jwirfs-brock i'm finding that this might work better if the details which aren't shown initially are shown in a popup bubble rather than inline. 

when shown inline, the layout must shift to accommodate the new content, and i think it can be confusing.

thoughts on that?

(note: this can be seen on deploy at the moment (8pm weds night), though no guarantees about how long it will be there in current state)

**Comment by jwirfs-brock** [comment]
@patternleaf I just had a chance to take a look. I agree that with the inline approach, the layout is a bit odd. Go ahead and try the pop-up.

**Comment by patternleaf** [comment]
hey @jwirfs-brock , circling back around to this. i couldn't get the popup thing to work well. instead have implemented a  slide-down container a la iOS folders. please let me know if/when you want to check this out—i'll make sure it's deployed on deploy so you can take a look.

![Screenshot 1:9:13 3:19 PM](https://f.cloud.github.com/assets/73439/54928/db9b1b98-5aaa-11e2-9c6b-dfafe6b9ef91.png)

**Comment by jwirfs-brock** [comment]
@patternleaf I have some time today to look at it. Is it at http://deploy.atlas.terrorware.com/en/build/? I'm not seeing it at the moment...

**Comment by patternleaf** [comment]
@jwirfs-brock i just switched the instance back over and will leave it for a while tonight.

**Comment by jwirfs-brock** [comment]
Can we have a symbol to the left of the the "find out more" link (a blue version of the chevron on the help age: http://floodlightproject.org/en/help/), so that it's clear to a user that it's a drop down, not a link that will take them away from this page?

Should we have the example links open in a new tab?

Other than that, I think it looks good.

**Comment by patternleaf** [comment]
ok, @jwirfs-brock i've implemented those two things and did a little cleanup in the code. going to close this.

**Comment by ghing** [comment]
@patternleaf, I tried to take a look at this, but I think you had already reverted the deploy instance.  Did you test this in IE?  How would this work with more than 2 templates?

**Comment by patternleaf** [comment]
@ghing ah, yeah, i'd switched the instance over to a different branch. it's now back on the 383 branch and i'll leave it up for a bit. seems to work fine in IE9. let me know when you've checked it out and if you have any suggestions/additions.

**Comment by patternleaf** [comment]
also @ghing i was testing with 4 templates. should be good to go on any number so long as there are two templates per row.

**Comment by ghing** [comment]
@patternleaf, Can you try testing with an odd number of templates?

Also, one issue I noticed is that if the user scrolls down to the last row of templates and clicks the "Find Out More" link, the info area slides down, but it's hidden "below the fold".  One solution would be to scroll down to the middle or bottom of the now-revealed element, but I don't know if that adds too much complexity.

**Comment by ghing** [comment]
I would also recommend putting some kind of separator (a comma perhaps) between the example stories.
