### ISSUE TITLE
IE users should get a message telling them to upgrade to the most recent version

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#393]
I'm flagging this as critical, but the other IE issues aren't.

@bpawlak Can you recommend some language for the message, and I'll tweak?

**Comment by bpawlak** [comment]
I've always started with something like this (http://code.google.com/p/ie6-upgrade-warning/) as a basis.  Of course, we'd want to update the script if we decide to use it (Firefox 3+ is now actually Firefox 16.0.1).  Otherwise, the message is polite and concise and provides the links to directly download what's being suggested.

**Comment by ghing** [comment]
I'll look to ie6-upgrade-warning as a reference for the language to use.  Rather than using that code, however, I'd like to a) present the warning in a manner more consistent with our UI practices and b) check for supported browser features rather than specific browser versions.  That way we can give a friendly message for unsupported browsers we don't know about.

For detecting the file API, see http://www.html5rocks.com/en/tutorials/file/dndfiles/#toc-selecting-files

For detecting pushState, see http://stackoverflow.com/a/6825002

Both of these browser features are things that we can work-around for older browsers, but lack of support for them in IE is breaking things at the moment.

**Comment by ghing** [comment]
The builder now shows a message in the alerts bar for browsers that lack support for required features.  These changes are live on dev.

Should I do something similar for the explorer?  It might be a little harder because I'm not sure what's missing that breaks things in the Explorer on IE, but I can try to figure it out.

Should we provide a 'read-more' link to a page that describes this problem in-depth and outlines our intentions for browser support?

**Comment by jwirfs-brock** [comment]
We should definitely include information about supported browsers. That
should probably go on our "Help" page.

**Comment by bpawlak** [comment]
I would put the message on the sign-up page of the site itself, not just the builder...

**Comment by jwirfs-brock** [comment]
Ok, here's some text we can display at the bottom of the signup page"

"Floodlight works best in Firefox, Chrome or Internet Explorer 9. If you are using an older browser, we recommend updating to the latest version. You can find more information here."

The last sentence will link to the browser support section within the Help (which I'll create shortly).

Do we want to provide recommended versions for Firefox and Chrome, or just say that users should update to the latest version?

**Comment by bpawlak** [comment]
I would just say the latest version.  If they don't have it, any link to download it (mozilla.org or www.google.com/intl/en/chrome/browser/) is going to be the most recent version

**Comment by ghing** [comment]
I'm going to leave off Internet Explorer 9 from the supported browser list for now because that browser lacks support for some of the features that we currently require (the History and File APIs).  As we discussed before I think IE 9 is a good target for IE support, but I'll need to just do more testing and workarounds for some of these things.

I'm going to go test this on IE right now.

Also, I'm only showing this warning if the browser lacks the specific features that we need.  Let me know if it should always be shown.

**Comment by jwirfs-brock** [comment]
I added in placeholders at the end of the Help section (http://staging.floodlightproject.org/en/help/) for the following questions:

"What web browser should I be using to read and build stories on Floodlight?"
"Can I use Floodlight in Internet Explorer?"

@ghing Editing them from the Django admin, they are at the bottom of the Help page, in the Text plugin in the Twocol-Content element. They have anchors id="browser" and id="IE".

**Comment by ghing** [comment]
@jwirfs-brock, updated the text in the help page.  Assigning this back to you for review.

**Comment by jwirfs-brock** [comment]
Looks good. Closing.
