### ISSUE TITLE
Changing layout incorrectly removes assets

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#413]
I had an image asset in the left-side of a side-by-side layout and I changed the layout to above/below.  When I did so, my image asset was removed to the Asset container, even though there are still 2 content containers in the section.

**Comment by ghing** [comment]
This is the expected behavior, when a layout is changed, all assets are removed and added to the asset drawer.

It works this way as I remember a conversation a long time ago where we decided that we didn't want to make any assumptions about how assets would be mapped across different layouts.  

This could change (post-launch).  Off the top of my head, it would involve defining a weight for the different containers and copying assets from lowest to highest weight to the new containers from lowest to highest weight, until you run out of new containers.

**Comment by bpawlak** [comment]
Ah, yep.  I think that _is_ what we decided - at least for initial launch.  Closed for now.
