### ISSUE TITLE
On Organizations page, images are overlapping with organization descriptions

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#419]
See http://staging.floodlightproject.org/en/organizations/

It looks like we don't have any resizing implemented for the organization page, so images that are wide are overlapping with the text for the organization descriptions. The same thing is happening with the project page.

For now, because we need to upload the images manually through Django admin, we can just make sure that every featured image we set for an organization is small enough that it doesn't overlap. 

Eventually, though, we'll probably want to either implement some re-sizing or enforce a maximum width for the images.

@ghing or @patternleaf do you happen to know the max width of that featured image column so I can crop or resize the images appropriately?

**Comment by ghing** [comment]
It looks like the images that are overflowing are ones that are just linked to from an external site (with no oEmbed).  We'll never be able to resize the actual image unless we make a local copy of all those images and manipulate them, which I think is a bad idea.  I think I can keep these images from overflowing their containers by scaling them with CSS via a `max-width` style.

Images uploaded will automatically be scaled to the correct width (right now 222px wide).  The size of the default image is 222x132px, but that's all subject to change since this layout is pretty quick and dirty.  We might want to revisit it if you have any feedback about how these pages should look.

**Comment by ghing** [comment]
Confirmed that max-width fix works.  Fix coming shortly.
