### ISSUE TITLE
Twitter URL link shortening works intermittently

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#421]
Check auto-shorten link function in tweets sent from stories. Works intermittently. 

Sometimes appears as long URL but doesn't display message that URL will be shortened. Viewing the tweet on Twitter.com in Firefox, the URL is not shortened.)

Other times, it affects character count. 

@Jordan what browser were you using last night when we encountered this problem during the demo?

See: http://webapps.stackexchange.com/questions/22601/why-doesnt-twitters-url-shortening-always-work

**Comment by jwirfs-brock** [comment]
It was Firefox.

**Comment by jwirfs-brock** [comment]
Note that this is also User Story 16

**Comment by ghing** [comment]
I wonder if the Twitter popup doesn't support the auto URL shortening as you type.  We'll have to experiment a little bit, but if it is the case that auto URL shortening doesn't work in the share popup, our only option would be to always shorten before we send it to Twitter.

**Comment by ghing** [comment]
Assigning to @patternleaf.  I suspect that this might just be because the shortening javascript doesn't get loaded in the twitter popup that's fired by AddThis.  You might want to  mock up a static HTML page sharing a floodlight URL using using Twitter's native Tweet This button to see if the behavior persists.

If it seems like this issue is on Twitter's side, we could add logic to shorten before sending to AddThis/Twitter, but we should talk about that first.

**Comment by ghing** [comment]
To replicate:
- Log into Twitter in your browser
- Visit a story detail page, e.g.: http://floodlightproject.org/stories/open-door-youth-gang-alternative-a-mile-high-unite/
- Click on the "Share This Story" icon
- Click on the Twitter icon

Desired result:

A popup window should be shown with the story title and either:
- A shortened version of the URL
- A message that the URL will be shortened

What happens:

A popup window is shown with no shortened URL, no message about URL shortening,  and a negative character count:

![floodlight_addthis_twitter_sharing](https://f.cloud.github.com/assets/110420/50809/ae772aa8-59b5-11e2-9993-740c13fb3d99.png)

The suggested text in the popup is:

> Floodlight | Open Door Youth Gang Alternative, a Mile High United Way partner, is changing lives beyond gang violence | Floodlight http://floodlightproject.org/stories/open-door-youth-gang-alternative-a-mile-high-unite/#.UOxSLXoVXhA.twitter

This is 240 characters total and the non-URL portion of the text is 131 characters.

I tried pasting the entire tweet into the normal tweeting interface on the Twitter website and it showed the same result (no shortened URL, no message about URL shortening, a negative character count)

![floodlight_tweet_twitter](https://f.cloud.github.com/assets/110420/50831/8cc41fe6-59b6-11e2-8fb0-b1905d3aa2f9.png)

As an experiment, I removed the redundant "| Floodlight" from the end of the Tweet text, so the text is now:

> Floodlight | Open Door Youth Gang Alternative, a Mile High United Way partner, is changing lives beyond gang violence http://floodlightproject.org/stories/open-door-youth-gang-alternative-a-mile-high-unite/#.UOxSLXoVXhA.twitter

So the text is now a total of 227 characters and 118 non-URL characters.

Twitter reported that this was now an OK length with 2 remaining characters to spare.

When I tweet this, it shows up as the following on Twitter:

> Floodlight | Open Door Youth Gang Alternative, a Mile High United Way partner, is changing lives beyond gang violence http://floodlightproject.org/stories/open-d…

What's going on?

At some point, Twitter decided to start wrapping ALL URLs in Tweets in t.co URLs and using something called Tweet Entities to render the original URL if possible.  So, Twitter automatically shortens the URL using its own shortening service and also stores the original URL for display in Twitter and other apps.

More information about Twitter's link shortening is at:

https://dev.twitter.com/docs/tco-link-wrapper/faq

I think this is all in flux, but Twitter currently shortens long URLs down to 20 characters (though this is subject to change as the number of URLs grows).  So the character count reflects the non-URL text plus 20 characters for each URL longer than 20 characters.  So, in our original example, there are 131 non-URL characters plus 20 for the shortened URL for a total of 151 characters, 11 over the 140 character limit.

Solutions we can't do:
- Get a "this URL will be shortened message" using the default Twitter interface. It looks like they eliminated this from their UI and we can't add it back.

Solutions we should do:
- Remove the redundant "| Floodlight" from the Tweet text. I need to figure out why that's there, but I suspect it was added before the site name appeared in the page title.

Solutions we could do:
- Remove "Floodlight" altogether from the default Tweet text. I think this isn't too hard.  It loses some branding, but the floodlightproject.org domain should show up in the Tweet in most apps and on the Twitter website.  Let me know what you think about this.
- Build our own Tweet interface that shows a "This URL will be shortened" message. I don't think this is a very worthwhile use of our time
- Shorten the default tweet text so it's always short enough to be tweeted without editing. This is a little tricky because it requires checking how long Twitter's shortened URLs are (remember, this is 20 now, but can change over time) and might require breaking out of AddThis.  I'm not sure if this is a great option because it's a little elaborate for not much added usability.  I feel like if users are tweeting through the widget, they've used Twitter before and understand how URL shortening works.  I also imagine that a human-shortened tweet is more compelling and readable than one we shorten by chopping off the end of the text.
- Cap story titles in the builder, or at least issue a warning that they're pretty long. This wouldn't guarantee that a Tweet is always too long, but would help make it less likely that the default Twitter message is unreadable.  This might be worthwhile because I feel like some of the titles for stories are already too long and trying to steer users to a consistent length title would help us a lot with making content elements a more fixed size in visual layouts.

**Comment by ghing** [comment]
"Floodlight" appears in the tweet text twice because it is in the actual HTML TITLE element twice.  It is prepended by the `story_detail.html` template and appended by the `base.html` template.  I think it's better to append, so the story title starts showing up in spaces where space is limited, so I'm going to remove it at the beginning. @jwirfs-brock, @tekhneco let me know if you have strong feelings that it should come first.

**Comment by ghing** [comment]
After removing the redundant "Floodlight | " from the beginning of the story detail page title, we now have approximately 106 characters to work with (140 - 20 for shortened URL - 13 for " | Floodlight" - 1 for space between title and URL) when Tweeting the story.

I took a quick look at the story title lengths and only 1 story has a title that is too long to fit in a Tweet: "Taking Action for the Social and Emotional Health of Young Children: A Report to the Community from the Denver Early Childhood Council"

Even if " | Floodlight" is removed from the title, this title still doesn't fit.

Based on this, I don't think it's worthwhile to add logic to remove "| Floodlight" or  auto-shorten the logic when creating the default tweet text.

I'm going to close this issue as removing the redundant site name in the page title for the story detail page makes nearly every story tweetable without editing.  The inconsistancy that @tekhneco reported may have been a result of Twitter changing its URL shortening strategy.  After my testing, I now feel confident that the user's experience sharing a Floodlight URL to Twitter via the AddThis widget is consistent with Twitter's general URL shortening behavior.

While warning users about long titles in the builder seems like it might still be worthwhile, I think that's out of scope of this particular issue. We can open a separate issue if we decide we want to implement this feature.

**Comment by jwirfs-brock** [comment]
I agree that the notification about the title length is important, but beyond the scope of this issue. I'll open an issue for it and it can be a "rainy day" item.
