### ISSUE TITLE
Need to analyze and fix how 2nd & 3rd level navigation works

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#426]
I've been trying to make heads or tails of how the content in "Grow Your Skills" and "About" is organized and displayed via navigation (top nav and side-nav) and I'm completely lost...  Soon after launch, I'd like to address site navigation and layout/feedback of the navigation as a high-priority item.

**Comment by bpawlak** [comment]
I'll post an example of how the "Partners" page should look in the "About" section.  You'll note that "About" in the main nav is highlighted (since we're in that section of the site) and the "Partners" left-nav item is also differentiated (providing feedback as to where the user is within the About section.  (I've also left-justified the page heading as we've been discussing - see #433 and #576)

**Comment by bpawlak** [comment]
![nav](https://f.cloud.github.com/assets/2250519/79628/ff06e79a-61be-11e2-95c3-d3a2363057c9.png)

**Comment by bpawlak** [comment]
Similarly, the dropdown menu in the main nav should be changed to match the subsections within "About." In this case, we're making 4 separate pages:
1) the main About page (i.e., what is floodlight)
2) The Vision
3) How it Works
4) Supporting Foundations and Partners

![top_nav](https://f.cloud.github.com/assets/2250519/79652/4646dc36-61c0-11e2-86be-bfbb26950386.png)

Note that I've added some extra spacing between the list items to make it easier to see that they are 4 independent links rather than just line-wrapped text, but see my comment related to the "Grow Your Skills" dropdown, below.

**Comment by bpawlak** [comment]
The "Grow your skills" dropdown should be changed so that the 4 main sub-sections of the "Grow Your Skills" section are delineated.  

![top_nav_gys](https://f.cloud.github.com/assets/2250519/79708/0f7e5942-61c3-11e2-8c56-daccf2d4f873.png)

_Note_ I'd recommend that the "About" example (above) should technically have the same layout as the "Grow Your Skills" example shown in this comment, but we can discuss...

**Comment by bpawlak** [comment]
And the sub-nav within "Grow Your Skills" can also be simplified:

![nav_gys](https://f.cloud.github.com/assets/2250519/79718/6a525544-61c3-11e2-9962-92f39533a0ce.png)

Note that we'll have to re-write some content... the "Workshops" heading shown in the main body content in this image wouldn't go on the "Overview" page... it would be part of the "Storytelling Workshops" section.

**Comment by jwirfs-brock** [comment]
@bpawlak Your recommendations make sense for the "About" section, but we should discuss what to do with "Grow Your Skills." 

Originally, the concept was that we'd have a series of subject areas where we offer tutorials and resources. Data Analysis and Visualization isn't necessarily a second-level nav item -- it's just the only tutorial that we have right now. When we do build out this section of the site, the nav structure will have to change to reflect this.

However, now we've started posting more tips and tutorials as stories created through the builder -- not just page content. So this area of the site needs some significant re-thinking. Instead of having sub-nav pages, we may want to embed the relevant Floodlight stories.

**Comment by jwirfs-brock** [comment]
Oh, and I agree on the restructuring of the mega-menu navigation. One thought on the "Grow Your Skills" section is we could have "Tips and Tutorials" where "Data Analysis & Visualization" is now, and have the list of existing tutorials under that heading.

**Comment by bpawlak** [comment]
So we should probably have a conversation that is specifically related to longer-term information architecture issues and plans.

**Comment by jwirfs-brock** [comment]
Yes, we do!

**Comment by ghing** [comment]
Assigning this 5 points just because there still seems some analysis remaining.  It will probably make sense for @patternleaf and I to make sub-issues out of this once the requirements are finalized.

**Comment by jwirfs-brock** [comment]
New menu structure is here: https://docs.google.com/spreadsheet/ccc?key=0AripktENBWzTdDZmejBwWmlCYU5xLV9CZUIya2ZBeEE#gid=0

New content outline is here: https://docs.google.com/document/d/1jgwx9NBwuFIbZxSAuwjlhkfqGwss-V9n4eeQhgRrlW4/edit#heading=h.ecb66kh5mipi

@bpawlak If @ghing and @patternleaf need further details (like wireframes) can you provide? Thanks.

**Comment by ghing** [comment]
@jwirfs-brock, I'm a bit worried about the "Latest Updates" and the "News and Events" landing page because these involve new content (or curation of content) that isn't on the site right now (whereas other items seem like they're mostly cleaning up/reorganizing existing content).  The "Info to Add" seems blank in the "Content Outline" doc for these two pages. To move forward, I feel like I need to know:
- What content will live in these pages when we launch the content re-org?

Then I'll likely have a few follow up questions depending on the content.

**Comment by bpawlak** [comment]
I think the goal is to create new content

---

**Comment by jwirfs-brock** [comment]
Sorry, I'm buried in catch-up this morning. Yes, I will be creating new
content for those. I'm just a bit behind on it because I've been out of the
office/traveling. I'm planning on spending some time today to get the
updated content. We can delay these issues pending the content updates.
Sorry to be the blocking factor on this one...

**Comment by jwirfs-brock** [comment]
@ghing I'll assign back to you once the content updates are ready.

**Comment by ghing** [comment]
@jwirfs-brock: Are you going to put the content for the `News & Events` landing page and the `Latest Updates` in the Google Doc or directly into Django CMS.  What I want to get a sense of is what new data models and templates (if any) we'll need to implement these new areas of content. When I have a better sense of the content I can make better recommendations for the implementation, give better time estimates and trade-offs and start building.

**Comment by ghing** [comment]
Based on taking a more close look at this it looks like the sub-tasks will be:
- Create new Page content - Create new Pages and move content around in existing Pages and nest pages in the correct hierarchy in Django CMS (Jordan, with Django CMS usage support from Geoff)
- Redirect (or otherwise handle) existing content - If a certain URL path is going away, we should set up redirects to where that content now lives. (Geoff)
- Set up automatic sidebar menus for nested pages - I took a first pass at this when I implemented the wireframe theme way back in the day, but I'll need to revisit this (Geoff)
- Update the megamenu navigation to reflect the new page organization (Eric or Geoff)
- Set up active section highlighting (see @bpawlak's comment in megamenu (Eric or Geoff) 
- Make Django models, views and templates for the `News & Events` page (Geoff or Eric)
- Make Django models, views and templates for the `Latest Updates` page (Geoff or Eric)

I'm going to hold off on creating new issues for these until I'm able to touch base with Jordan.

**Comment by jwirfs-brock** [comment]
I'll be planning out the new content in the Google Docs.

Ultimately, I'd like to be able to update the new content through the
Django CMS.

I think the only substantially new piece to the data model would
be incorporating the news item that you built for the  homepage widget into
one or both of those pages, so that content would only have to be added
once. Is that what you meant?

We maybe also need a new page template (i.e., a new layout besides the (a)
single column and (b) single column on top, two below -- which I believe is
only being used on the "About" page at the moment).

**Comment by ghing** [comment]
@bpawlak, I wanted to get some clarification about the proposed new content structure:
- Are each of the 2nd level items separate Pages? That's my impression from your earlier comments, and what makes most sense to me, but I wanted to confirm.
- What will live in the top-level page for each section, e.g. "About" or "Grow Your Skills"? A quick summary of the content below it?

**Comment by jwirfs-brock** [comment]
@bpawlak In the updated Floodlight Information Architecture, we don't have the information that is on the policies page (http://floodlightproject.org/en/policies/) :
- Policies overview (user-friendly language)
- Community values statement (user-friendly language)
- Master terms of service (long, legalese)
- Creative Commons use guidelines/tips (user-friendly language)

Would it make sense to put the user-friendly pieces (that is, everything except the master terms of use) on the "About" section, as second-level (or third level?) nav items?

**Comment by jwirfs-brock** [comment]
@bpawlak @ghing I added new content to the [News & Events](https://docs.google.com/document/d/1jgwx9NBwuFIbZxSAuwjlhkfqGwss-V9n4eeQhgRrlW4/edit#bookmark=id.4ipoulacdujo) and [About](https://docs.google.com/document/d/1jgwx9NBwuFIbZxSAuwjlhkfqGwss-V9n4eeQhgRrlW4/edit#bookmark=id.8v6q4jbgtuu) sections.

When you get a chance, please review and let me know of the organization of it makes sense.

A couple of notes:
- For both sections, I added blurbs about the second-level pages on the top-level page. I think it makes it easier to navigate through the content, but if you think this is confusing/unnecessary, let me know.
- For the "News & Events" section, I recommend a two-column layout for the page content. One column would have the teasers for the second-level pages, the other would have a feed of the latest news items.Thoughts?
- I added back in the "How it Works" section in "About" because that graphic is almost complete.

I'm tackling the "Skills" section next, which is a bit hairier...

**Comment by bpawlak** [comment]
@ghing Yes, each 2nd level item is it's own page and the top level content is the same as the 1st element in the drop down.  Jordan will be working on content, of course, but it should include a summary of what's to follow in that section of the site (e.g., the "Grow Your Skills" page should give an introduction to the concept of growing one's storytelling skills as well as provide some insight as to what's to be found in each of the sub-topics.

@jwirfs-brock I took a look at the Google doc and think you're right on track.

**Comment by bpawlak** [comment]
@jwirfs-brock  I think the intro text and "Floodlight Community Values" and "Master Floodlight Terms of Use" can stay where they are.  The "Using a Creative Commons License with Floodlight" seems more like help text (since it's so related to the builder) and could go there _or_ perhaps add a modified version of it to the "how it works" page (and remove the detailed instructions for how to set the cc license within the builder)

**Comment by jwirfs-brock** [comment]
@bpawlak That makes sense. That's a good suggestion about the Creative
Commons info. Currently, we have the following in the Builder on the
Publish/Share page:

"All Floodlight stories will be published with a Creative
Commonshttp://creativecommons.org/ license.
Find out more about why we decided to use Creative
Commonshttp://floodlightproject.org/policies/#community-values
 and how to choose a
licensehttp://floodlightproject.org/policies/#using-creative-commons
."

But we could include the full content on the help tab.

My other thought about the policies stuff is that, as it is now, you can
only get there from the tiny "Policies" link way at the bottom. It might
make sense to at least link to them someone on the About page.

**Comment by jwirfs-brock** [comment]
The top-level content for skills is now at: https://docs.google.com/document/d/1jgwx9NBwuFIbZxSAuwjlhkfqGwss-V9n4eeQhgRrlW4/edit#bookmark=id.k4ype1kjirvy

Notes:
- Still need to complete second-level pages in Skills section (right now, only have "Data Analysis and Visualization").
- I limited the list to reflect topics we have content for from the NNE Story-Raising. Until I can adapt all of that into topic pages, we'll either need to have place-holder pages or a "coming soon" note on the top level page.

Question for @ghing :
- If we want to add topics in the future, and have that reflected in the navigation, will we be able to do so through the Django admin/CMS?

**Comment by ghing** [comment]
@jwirfs-brock, if we're just talking about sub-pages of a section, they can be added via the Django admin.  I'm trying to make the navigation as automatic as possible, but there should also be the ability to edit the sidebar manually if needed.  So yes, unless I'm overlooking an edge case, new topics can be added by just creating new Pages in the Django admin with the correct parent.

**Comment by jwirfs-brock** [comment]
@ghing what about updating the list as it appears in the megamenu nav? Can
that also be via the Django admin?

**Comment by ghing** [comment]
The megamenu is hard-coded in a HTML template, but we can probably wire that up to the Page navigation structure.  I'll take a look at any considerations for this as I get further into the implementation for this issue.

**Comment by jwirfs-brock** [comment]
@ghing It's not something that would be happening very often, so this is
only something we should do if it's an easy fix.

**Comment by ghing** [comment]
@jwirfs-brock 

Two things:
1. Let me know when you've implemented most of a section's worth of level-2 pages. I've got the basics working for listing sub-pages along with their teasers and I wanted to start testing it with real content as I work through the styling/layout
2. Based on the content Google Doc, it looks like the sub-page list might occur at different points in the page.  For instance, in the _Grow Your Skills_ page, it seems like it's intended to appear at the top of the page.  For the _About_ page, the list of sub-pages seems like it goes at the bottom.  I can make it work so that the list can go in variable places, but I wanted to make sure that this was intentional rather than just a matter of how the content was entered in the Google Doc.  If the different positions are intentional, should the sub-page lists still be styled the same?

**Comment by jwirfs-brock** [comment]
@ghing:
1. The About and News & Updates sections are set up with all the second-level pages with the teasers (but the second-level pages don't have their full content yet). Skills still needs a couple more second-level pages.
2. Yes, you interpreted the content outline correctly. But you could also look at it as: Skills and News & Events, we want (a) top-level page description, then (b) secondary teasers. On About, it's essentially the same, but (a) is just a lot longer.

The styling for the sub-page lists can be same on all pages.

**Comment by jwirfs-brock** [comment]
@ghing Here's the punch list of remaining items for the content updates:
https://docs.google.com/document/d/1jgwx9NBwuFIbZxSAuwjlhkfqGwss-V9n4eeQhgRrlW4/edit#bookmark=id.7bqvr0b4n8nx

**Comment by jwirfs-brock** [comment]
@ghing I think I broke the "Grow Your Skills" page when I was trying to edit it.

In response to your comment on the "Content Outline" doc ("In this document, there are a number of places where the page titles, the titles in the megamenu nav and the title in the sidebar nav differ.  It’s important to balance clarity and consistency for the users with making things look good in sometimes limited space."), I decided to change the page name of "Grow Your Skills" to just "Skills" to match the menu. I also changed the slug.

I realized that when I did that, the megamenu was wired up to the /grow-your-skills slug, so I changed it back.

I also changed the page title back.

Now, http://floodlightproject.org/en/grow-your-skills/ is showing the content for the About page (not sure how/why that is happening), but displaying the correct children.

**Comment by jwirfs-brock** [comment]
@ghing Note that the correct content is saved in the admin at http://floodlightproject.org/en/admin/cms/page/2/

**Comment by jwirfs-brock** [comment]
@ghing Other than the plugins that  need to be moved once the updates to the template are pushed to production, and the bug with "Grow Your Skills", the current updates are ready to go. Let's check in tomorrow AM to arrange a work plan for getting them out by end of day.

**Comment by ghing** [comment]
@jwirfs-brock The issue with the "Grow Your Skills" page is that there aren't any plugins in the body placeholders.  The text that you're seeing is just fallback text that gets shown when no placeholder content is defined that just happens to match the "About" page text.  

The quick fix is to put some content in a text plugin in the "Twocol-Content" placeholder.

**Comment by jwirfs-brock** [comment]
Weird. On the admin page I'm seeing text in the placeholders.

**Comment by jwirfs-brock** [comment]
Ok, now they are gone. So...when I changed the page name somehow the text
disappeared! Looks like I'll have to re-create it. Ugh, annoying!

**Comment by jwirfs-brock** [comment]
@ghing Ok, sorry about the confusion. It's Monday morning and I haven't had my coffee yet.

 I think what is happening is that the "Skills" page should just  have:
- description
- teasers

So no body content. If that's the case, should we put in an empty text plugin in the placeholder?

**Comment by ghing** [comment]
@jwirfs-brock That's what I figured.  Yes, just throw an empty text plugin there for now.

**Comment by jwirfs-brock** [comment]
@ghing Ok it's done.

**Comment by ghing** [comment]
I've deployed the updated section landing templates and updated menus into production.  I'm going to close this issue. There are still some content updates that need to happen which are tracked in the [Content Outline](https://docs.google.com/document/d/1jgwx9NBwuFIbZxSAuwjlhkfqGwss-V9n4eeQhgRrlW4/edit) document. 

If there is any remaining polish, that arises, please open it as a separate issue.
