### ISSUE TITLE
contributors have a public profile page that includes a listing of stories they have created (user story #98)

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#461]
User Story #98

**Comment by jwirfs-brock** [comment]
I have a few thoughts about the format of the user profile page:
- The profile image is a bit large, which pushes the story list below the fold. Can we make it smaller?
- As far as I can tell, the only way to set a profile image is to connect to a social media account. I think that's probably because we didn't explicitly include the user stories for that in Iteration 8 (although we have done analysis for it already). We should make sure to include this soon in an upcoming iteration, but until we do, we probably need a note that says, "To include a user photo, connect  your Floodlight account with your Twitter or Facebook account," and links to where you do that in "My Accounts."
- There should be a link to view the public-facing profile from the "My Accounts" page. Maybe in the side nav we can have a "View my public profile" link? @bpawlak suggestions?

**Comment by bpawlak** [comment]
I wouldn't put the "View my public profile" link in the side-nav (the side nav is reserved for moving between the My Account sections (communications, profile, my stories, etc.).  Perhaps a button like on the admin pages to launch the public profile page?  Or, are we displaying what the url to the user's profile page is?  If so, then that link can open the public-facing profile page.

Q: Will the profile edit page have a similar layout/styling as the organization and project pages?  (with a cancel link and "Save Changes" button (instead of e.g., "Create Project")

**Comment by ghing** [comment]
@bpawlak I had a similar thought about the "View my public profile link" needing to be different.

Right now, there's no editing view for the public profile since it just has a list of a users stories and affiliated projects/organizations and the profile image is automatically sucked in.

**Comment by jwirfs-brock** [comment]
You're right, the sidebar isn't the right place for it. But I do think if
users have a public-facing profile, even if right now it's uneditable, they
should have an easy way to view it. (Right now, the only way to see it is
to click on the author from the story detail page.)

**Comment by bpawlak** [comment]
Ah.  Yes, forgot about the programmatic generation of it.  Still, we should probably reflect what the public URL is to the user and clicking on that link should open the profile page.  I would put the link at the top of the Account Information editing page (http://floodlightproject.org/en/accounts/)

**Comment by ghing** [comment]
@jwirfs-brock, as of commit 6dce6c9712b957b67a6b7fa0b84482de3f77cfbc, fixes addressing your 3 concerns have been pushed to the development and staging instances.

I adopted @bpawlak's suggestion of putting the public URL at the top of the "Account Information" page and put information about how the profile image is set there.

As a note, the current logic for selecting the profile image uses the user's Facebook profile image if they've connected a Facebook account.  If they haven't it tries to use a Gravatar image.  If that fails, the default image is used.  The Twitter profile image is not retrieved because there isn't a "legal" way to use the Twitter API to just get a user's profile image in a way that is appropriate in an IMG tag.  In order to get the profile image from Twitter, you have to make a request to the Twitter API and parse the JSON response. This seemed a bit heavyweight to deal with for a first pass at this feature, but we can address that restriction on the API at a later point if we want to give users a lot of control over setting their profile image.

**Comment by ghing** [comment]
@jwirfs-brock, I'm assigning this to you for review.  Please close it if this looks good, or assign it back to me if it needs another pass.

**Comment by jwirfs-brock** [comment]
@ghing  Great, reviewing now...

**Comment by jwirfs-brock** [comment]
@ghing This looks good. Just one comment before we are ready to close. On stating, the link for "Your public profile page is viewable at" is displaying staging.floodlightproject.org/ETC... but on dev it's just using floodlightproject.org/ETC.... (so you can't test out the profile link there).

Just want to  make sure that when we deploy, we are displaying the correct link.

Other than that, it's good to go.

**Comment by ghing** [comment]
@jwirfs-brock The issue with the link URL has to do with a setting that I just didn't bother to change on the Development instance, so it's using the one from the production instance that came over when I synced the databases.  It will be correct in production.

**Comment by jwirfs-brock** [comment]
Great. Closing...
