### ISSUE TITLE
Problem with "Save" for published stories

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#477]
I was editing the Call to Action section in the story http://floodlightproject.org/stories/workshop-11-why-do-we-tell-stories/. I used the hard save, but the changes I made in the Call to Action were not reflected on the site. We have to do some further analysis to get to the bottom of this. This isn't the first time I've noticed editing and saving weirdness for published stories.

**Comment by ghing** [comment]
@jwirfs-brock, without yet doing doing a deep dive into this, I'd say this is because the change event on the call to action (and maybe other) forms isn't getting triggered.  So, the save button is saving the story model to the server without reflecting the changed form field.  As a temporary, internal work-around, I would try updating the field by triggering the auto-save (clicking somewhere outside of the call to action text area).  If that also doesn't work, please add a comment saying so to this issue.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
