### ISSUE TITLE
Can't use "back" button from story detail page if you've launched the viewer in a modal window and changed sections

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#487]
**Update:** with changes to the viewer (namely, getting rid of the scrolling navigation).  I've updated the title to reflect this and I'd like up how to replicate this as it's not entirely clear from the title.
## To replicate
1. Visit the Explore page
2. Click on a story title to navigate to a story's detail page
3. Click on the "View Story" button to launch the story viewer in a modal window
4. In the story viewer, click on the "Next" button to advance to the next section
5. Close the modal window
6. Click on the browser's back button
## Expected result

The browser navigates back to the Explore page
## Observed result

The browser stays on the story detail page

Original report from @jwirfs-brock:

> From the story detail page, you can use the browser's back button (to go back to the Explore page, for example) 
> before launching the story viewer, of if you've launched the viewer but haven't scrolled (works if the viewer is open or 
> closed). 
> 
> However, if you launch the viewer and scroll, then you can't use the back button.

**Comment by jwirfs-brock** [comment]
I know we haven't assigned this to an iteration yet, but @ghing I was wondering if you'd looked at this at all. It's one of those seems that seemed minor at first, but the more I use the site the more annoying it gets.

**Comment by ghing** [comment]
@jwirfs-brock I haven't looked at this yet.  From reading the description, I think it might be related to the IFRAMEd viewer's use of the History API (so that each section in the viewer has a unique URL) and this clobbering the state of the parent window's history.  I'll have to do some testing to see if this is actually what's going on.

**Comment by ghing** [comment]
Giving this a somewhat higher point estimate (and the analysis tag) as some testing is still required to figure out the underlying cause.

**Comment by ghing** [comment]
Assigning this to you, @patternleaf, this would be a good one for you to take.

**Comment by jwirfs-brock** [comment]
Note that if you've done steps (3) - (5) above, but then refresh the page
before (6), you get the expected result.

**Comment by patternleaf** [comment]
to update: the fix in 11869f3 works for Firefox but not for Chrome. pinning down exactly what's going on in both browsers is proving to be pretty tricky. it seems that behavior of the history API wrt iframes isn't really consistent across browsers. i have an alternative fix which seems to work for Chrome but not Firefox, but it's unclear as yet what the "right" fix for this will be.

**Comment by patternleaf** [comment]
ok, after many attempts and investigations, i'm starting to suspect that the only reasonable way to address this is to not change any aspect of the browsing context's url/location/history when the viewer is in a modal context. we will lose the ability to use the browser's back/fwd buttons to navigate in the story, but this doesn't strike me as particularly evil, since we have our own fairly obvious back/fwd buttons. if a user wants to copy a link (say the anchor tag on a next/fwd button) those will still be valid as URLs to a story section, but the state of the viewer as modal/non-modal isn't stored in such a URL, anyway, so that's not a loss.

even then, some browsers treat iframe loads as writes to the history so there may still be some work to do.

@ghing is there a reason i'm not thinking of that would make this a bad strategy? also, is there already a way to easily tell from the view code and/or handlebars code when the viewer is being presented as a iframe?

finally, if it's necessary, do you have a sense for how difficult would it be to load the viewer modally without using an iframe?

**Comment by ghing** [comment]
@patternleaf 

I think it's fine to not update the browser's location/history when the viewer is shown in an iframe.  I think we should try to preserve it when opened in its own window/tab because I think it's nice for every section to have a URL, but when it's modal, we don't see the URL anyway, so there's no need to alter history/location.

I think the way to do this would be to add a querystring param to the viewer that toggles options related to the History API in the Backbone code.  For example /stories/some-story-slug/viewer/?iframe=true

The way to do this would be to check for the querystring parameter in `StoryViewerView` and use it to alter the context (I think the method is `get_context_data`).  I believe the parameters are available as `self.request.GET` or `self.request.REQUEST` (see https://docs.djangoproject.com/en/dev/ref/request-response/).  Then check/pass the option on to the instantiation of the main story viewer backbone view in the `storybase_story/story_viewer.html` template.

I would say it's difficult but not impossible or terribly crazy to render the viewer modally without using an IFRAME.  Let's try to not do that though, because I think supporting an IFRAME would be nice in case we ever want users to be able to embed the viewer on external pages.

**Comment by patternleaf** [comment]
So not relying on the Backbone router when the viewer is in an iframe seems to be doing the trick. What's not yet clear to me is what's up with connected stories and how those will relate to this. @ghing @jwirfs-brock do either of you know of a story with connected stories offhand, so I can make sure that's still working?

**Comment by jwirfs-brock** [comment]
Sure, this one has connected stories:
http://www.floodlightproject.org/stories/six-word-memoirs/
