### ISSUE TITLE
Errors when adding a story to a project or organization in the Django admin

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#495]

**Comment by jwirfs-brock** [comment]
I created a new project (http://www.floodlightproject.org/en/projects/near-northeast-denver-story-raising/). Then I tried to add a story to it (http://floodlightproject.org/stories/story/) in the Django admin from the story edit page. Because the story had a section without a name, when I clicked "Save" I got an error saying that the name of the section was a required field. (Section: Title: with the error message, "This field is required.")

So basically, in the story builder you can create a nameless section, but then you won't be able to edit and save the story with the nameless section in the Django admin. (Right now, this is just an admin problem and not a user-facing problem, because if you a member of a project and you want to add a story that you authored, you won't get this error. Until we give users more control over projects and organizations, we'll need all the managing of them on the admin side. But in the long term, I'm not sure how much admin control we'll need.)

Short term
- Can we make the section name an unrequired field to save in the admin?
- Is there a way to associate a story with a project without going into the story edit page? Right now, on project page -- example: http://floodlightproject.org/admin/storybase_user/project/14/ -- you can't add stories the way you can add users or organizations. Could we do this?

Long term
- This raises a related issue: As I'm been observing people create stories, the concept of a section name is a bit counter-intuitive. (It makes sense in some contexts but not in others.) Much of the time, people don't even notice it is there and leave it as "New Section" or "Image and Text." Personally, I often delete it. At some point, we'll need to address this.

**Comment by jwirfs-brock** [comment]
I may be able to add stories with nameless sections to a project in the Story Builder, but to do that my account would have to be a member of that specific project. (This is why we need the concept open projects...)

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot.
