### ISSUE TITLE
builder does not load in IE8, Win XP

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#503]
JS errors:

Identifier expected: views.js line 750
Object expected: build line 689

**Comment by ghing** [comment]
After you finish up whatever you're in the middle of, can you dig into this a little bit more to figure out what's causing this?

**Comment by patternleaf** [comment]
so this is on account of the use of the word "class" as a key in various hashes. class is "reserved for future use" in ECMAScript/Javascript though in most reasonable implementations, it's reserved as an "identifier" and not an "identifier name". so for those implementations, "item.class" is legal (the kind of thing done in builder/views.js) but "function class() { ... }" is not legal. 

but then, we're talking about IE8 here, rather than a reasonable implementation.

at any rate i tend to avoid using class as a key name since i've run into problems with it before. an easy fix is to replace instances of bare "class" with "className", but (@ghing) it looks like there's some code that intentionally uses "class" as opposed to "className"? it wasn't clear to me. 

another option is to replace unquoted hash keys using dot syntax with quoted keys using bracket syntax. this is awkward, though. 

@ghing, do you want me to double-check the semantics of class vs className in the code and do the former fix? or do you want to check first/have insight off-hand?

(more info here: https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Reserved_Words)

**Comment by ghing** [comment]
Good catch.  I think I might have run into the reservedness of `class` (see the cssClass variable declaration), but didn't realize the full extent of it.  I think that replacing class with className is a fine fix.  There are a few caveats:
- You may also have to adjust the Handlebars templates in story_builder_handlebars.html to reflect the renamed hash key
- One place where I intentionally used class is in the return value of the `attributes` method of a `View` definition (see http://backbonejs.org/#View-attributes).  In this case, I bet we can get away with just quoting the hash key since these just get applied to the element's HTML attributes and I imagine the calling code just iterates through the keys.

FYI, `className` is a Backbone hook to specify the class attribute of the view's element.  If this is the use of `class` in my code, then I think it's ok to use `className`.  Otherwise, let me know and I'll offer up a suggestion for a replacement.  

Just let me know if you run into any issues or questions.

**Comment by patternleaf** [comment]
I recall checking this fix, but just to be sure I tried again. Unfortunately I no longer have an XP/IE8 environment. However, in Win7, using IE9 _in IE8 mode_ ... this seems to be fixed. I'm feeling like closing this is ok, but if others disagree, feel free to re-open.
