### ISSUE TITLE
Need to add a search feature to the "Help" page

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#507]
This is based on feedback from a user who tried to find out how to do something by going to the Help page, but then couldn't search for that specific problem. 

Ctrl + F doesn't work (at least not in Firefox) because it doesn't search the collapsed/hidden text.

**Comment by ghing** [comment]
Implementing a client-side search form is too heavyweight for such a singular use case.

I see two ways to approach this:
1. Detect Ctrl+F (and other search keystrokes) and open all the collapsed items
2. Break each FAQ entry into it's own content item (which would still be aggregated the way it is now) and index each entry in site search.  Then users could use the site search to search for FAQ items. The results would link to the single faq entry.  That page would have a link back to the entire FAQ list. This is a more complex way to address this problem, but a generally useful pattern that could be used for other non-story content in the future.

**Comment by jwirfs-brock** [comment]
@ghing Number 2 sounds like a better option to me. Some questions:
- Would users be searching **just** the FAQ, or the entire site?
- Would users enter their search terms into the same search bar that is ubiquitous at the top of the site, or would we have a different "Search the FAQ" field on the [Help page](http://floodlightproject.org/en/help/)?

**Comment by ghing** [comment]
@jwirfs-brock 

> Would users be searching just the FAQ, or the entire site?

The same search back-end would be used to search for stories, FAQ entries, and (if we want) Pages and other content.  You could narrow the search to only certain content types.  So the answer is both.

> Would users enter their search terms into the same search bar that is ubiquitous at the top of the site, or would we have a different "Search the FAQ" field on the Help page?

Either is possible. You should think about which you'd prefer.

**Comment by jwirfs-brock** [comment]
@ghing 
Right now our search feature just returns stories as search results, right? This issue could be a good stepping stone to expanding that search feature to also search non-story site content. But to do that, we'll need to have a way of showing what type of content is being returned (story, FAQ entry, page, etc.) That's something I think we can tackle at a later time. Until we do, I think it makes the most sense to...
- Have a "Search the FAQ" field on the Help page
- That only searches the FAQ entries

Does that sound right to you? If it seems like we're doing things out of order, let me know. We have received requests for making the FAQ searchable, but not yet for making the site searchable. But that doesn't mean that there aren't people out there who would like to search the non-story site content. 

Is there a way we can look at data from how the search feature is being used, including the search terms that have been submitted? Are people searching terms that seem purely story-related, or are they searching for other things, too?

**Comment by ghing** [comment]
> Does that sound right to you? If it seems like we're doing things out of order, let me know. 

It might make sense to make the site-wide search also return the FAQ entries. It's not terribly difficult to identify the type of search result returned (FAQ vs. story).  We can leave off indexing pages for now, but this will get us a lot of the way there.

> Is there a way we can look at data from how the search feature is being used, including the search terms that have been submitted? Are people searching terms that seem purely story-related, or are they searching for other things, too?

No. We could add in some hooks for this into Google Analytics if you think it's important for the future.

**Comment by jwirfs-brock** [comment]
Because we don't have a lot of feedback on this, it's hard to know whether users are using (or trying to use) the sitewide search box to a) find stories, or b) search for other site content, like FAQ. I'm not sure if I was trying to find (a) I'd want (b) handed back to me, or vice versa. Thoughts? I could just be over thinking this

One way to handle this would be to add some more advanced search features (i.e., you could tell it to return just stories, or all results, etc.), but I think that may be overkill. It doesn't make much sense to put a lot of time and effort into a feature that isn't really going to be used.

Can we at least see, from Google Analytics, whether the search box is being used at all? I'll take a look and see what I can find.

**Comment by ghing** [comment]
@jwirfs-brock, Look at analytics for http://floodlightproject.org/en/search/ and http://floodlightproject.org/search/

**Comment by jwirfs-brock** [comment]
@ghing Just based on the Google Analytics from the past month...
- Search was used 37 times (many of those were probably me, Wendy and Rebecca, but not all)
- Most of the search terms seem story related (i.e., people are using search to quickly find a specific story -- i.e., "dog food," "design thinking," "welton street"
- There was a search for "organization" that could have been a user trying to find information about how to create an organization
- There are a couple of topic searches, like "education" and "arts"

We can't read that much into this, obvious, because it's just one month's worth of data and we don't have a lot of it.

**Comment by jwirfs-brock** [comment]
@ghing Based on what we're seeing in the analytics, my suggestion is to return all results (site content AND stories), and clearly show whether a result is a story or site content so users can easily distinguish. In the future we might want to add a filter to the results, but I don't think we would need to do that in this iteration.

**Comment by ghing** [comment]
@jwirfs-brock That sounds good to me and is the simplest implementation as well.

**Comment by ghing** [comment]
@jwirfs-brock, I was going to put this off until I finished the email notifications feature, but wanted to touch base with you since you'll be out next week.

When designing an implementation for this feature, I wanted to get the desired functionality but not add too much additional complexity to the system given the specific nature of this feature.  We discussed some of the elements of the implementation above, but I wanted to clarify my ideas for the part of the implementation that you'll be touching as an editor of content.

This is the idea came up with:
- Re-use the help model that we're already using for builder help for the help page as well. You would put the question in the title field and the answer in the body field.
- Add a flag field to the model to indicate which help items should be included in the search index (the help currently on the help page) and which items shouldn't (the builder help).
- Create a custom plugin for the CMS that lets you select which help items appear in the help page and change the order.
- Write a script to scrape the current help items and automatically import them into the new scheme
- Add help items with the searchable flag set to the search index
- Update search results to include help items as well as stories
- Make a view to show individual help items (or link into the help page with a particular item opened - that would be cool but there might be some complications with the implementation that I'm missing) that will be accessed when clicking on an item in the search results

What this means for you:
- To add a new item, you'll have to first create it in the Django Admin. This is just like editing the builder help in the admin. You'll have to make sure to set the "searchable" flag to true
- Then you'll need to edit the Help page and add a new plugin for the help item.
- To remove a help item from the help page, just edit the page and remove the placeholder
- To remove a help item from the search index, you'll have to delete it or unset its "searchable" flag

Let me know if this sounds good for you, or if there's anything that seems overly annoying or functionality I'm missing.

**Comment by jwirfs-brock** [comment]
@ghing This sounds good to be. It's great that you'll be able to write a script to import the existing help items -- that was a question that I had, but you answered it with your outline of the implementation.
