### ISSUE TITLE
Incorrect Open Graph meta tags for Project and Organization detail pages and filtered Explore page

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#546]
Two errors encountered when manually adding project page links to a Facebook status update. 

1) When pasting the project page link, the summary is copy pulled from the Build a Story navigation mega menu.  

![FB-Project summary](https://f.cloud.github.com/assets/2329239/17966/a4690778-4891-11e2-9fcf-d4d732fda331.png)

2) When pasting the View all Stories page from a project, the summary is copy pulled from the map help text.

![FB-Project view all summary](https://f.cloud.github.com/assets/2329239/17968/ce20c600-4891-11e2-9335-823cf5db105c.png)

**Comment by wendynorris** [comment]
View via Add This share button to Facebook for Projects: 

![FB share direct from Project page](https://f.cloud.github.com/assets/2329239/17995/e2f206b0-4892-11e2-8f51-faa4f7dbe1a2.png)

**Comment by wendynorris** [comment]
Same summary bug for Add This share button to Facebook for Organizations: 

![FB share direct from Org page](https://f.cloud.github.com/assets/2329239/18007/80554dc2-4893-11e2-90cf-5d866c64e34f.png)

**Comment by ghing** [comment]
I updated the issue title to more accurately reflect the issue.  The original title was "Project/Org page summary text errors in Facebook"

**Comment by ghing** [comment]
Note that the issue with no summary showing up when sharing using the AddThis widget described in @tekhneco's [comment](https://github.com/PitonFoundation/atlas/issues/546#issuecomment-11462999) is probably due to the fact that she tried to share a link on staging.  Since staging.floodlightproject.org is protected by the basic authentication password, Facebook can't retrieve any of the metadata for content on the staging instance.  So, that particular behavior is to be expected.
