### ISSUE TITLE
Story Builder should issue a notification for long titles

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#562]
Anything over 106 characters will show up truncated in the auto-text that is generated when the story is shared via Twitter/AddThis.

We should issue a notification that alerts a user of this, and suggests that he/she write a title that is under this limit.

This is something that came out of the analysis of Issue #421.

**Comment by jwirfs-brock** [comment]
Suggested solution: Post an alert for any title longer than 100 characters (one that doesn't force a limit, similar to what we have for the Summary).

Note that for the titles of the 144 stories currently published:
- average length is 43 characters
- only 3 are longer than 100 characters
- max length is 134 characters
- min length is 8 characters

**Comment by ghing** [comment]
Where should the alert show up? Next to/below/above the input, or in the "alert bar" (which is where the colored error/success/information messages currently show up)?  Should there be an ongoing character count? What is the microcopy for the message?

Assigning to @jwirfs-brock for anwers.

I think this will be a 3-pointer just because we might have to refactor the character counting code used for the summary to implement a clean, multipurpose solution.

**Comment by jwirfs-brock** [comment]
Answers to @ghing's questions:

I suggest having the alert message show up **next to the title** (i.e. just to the right of it). @bpawlak might have a more creative suggestion (maybe highlighting the title in red or something?), but I am fine with a simple message to the right of the title that says, "Your title is long and will be hard for users to read. Consider a shorter title." or something like that (not the exact microcopy yet -- it should be friendlier).

I don't think we need to count the characters as we go...just post the alert once it goes over 100 characters because it's just an alert, not a forced limit.

**Comment by ghing** [comment]
@jwirfs-brock, note that the current title field takes up the whole width of the container:

![screenshot from 2013-06-18 13 40 14](https://f.cloud.github.com/assets/110420/670619/993f4d72-d846-11e2-9ab7-f10f7d5bed70.png)

I'm worried that such a long message as "Your title is long and will be hard for users to read. Consider a shorter title." might not easily fit in the height of the field.  It seems like we'd also have to make the title field more narrow (which isn't terrible as it reinforces the need for brevity), but would we then make the byline and summary fields narrower to match?

Can you mock this up to better describe how you imagine the alert looking to the side of the title input?

**Comment by jwirfs-brock** [comment]
Oh, sorry about that. On my screen it looked like there was some space next to the title:
![screen shot 2013-06-18 at 2 49 36 pm](https://f.cloud.github.com/assets/1020518/670675/eb5246c2-d847-11e2-8b6a-a629ee89a56c.png)

@bpawlak would probably be better at doing wireframes. Could you give us some options? Thanks.

I'm ok with it going below or above the title, too -- I don't have a strong preference, other than I'd rather it not to be in the alert bar.

**Comment by bpawlak** [comment]
I don't think it should be in the alert bar, either.  One thing we could do is change the "Edit your title" prompt to include something about "## characters or less is suggested" or "shorter is better" ... then we wouldn't have to worry about "alerting" users when it goes over 100 characters.  Also, add something to the help text for the "Story Information" section.

**Comment by ghing** [comment]
I like @bpawlak's "shorter is better" microcopy.  One option would be to make that change, take a snapshot of the average title lengths and see if they change for stories authored after the additional direction.

Another (not mutually exclusive option) would be an alert like the one for the summary that appears above the field on the right hand side. It could even say "Shorter is better" and have a tooltip that would give a more verbose message.

For a reminder of what the summary character length warning looks like, try copying and pasting a lot of text into the story summary textarea and you'll see it.

**Comment by ghing** [comment]
@jwirfs-brock, any final decision about how you'd like to approach this?

**Comment by jwirfs-brock** [comment]
I like Bill's suggestion about putting information in the title field. My only worry is that, once someone starts editing, that information will be gone. @bpawlak, any further suggestions?

How about "Edit your title here. Shorter is better - keep your title to 100 characters." in the title field. Could we then show the alert _above_ the title field, like this?

![title_alerts](https://f.cloud.github.com/assets/1020518/763116/e321ba90-e7f7-11e2-9171-a42a0dd7fd2c.png)

In this mock-up, I also made the title field red when it goes over. Thoughts on that?

**Comment by bpawlak** [comment]
Why not use that space to do something like Twitter does (http://cssglobe.com/lab/charcount/01.html)  ... real-time character counts have been in use for 10+ years, we might as well as take advantage of it.

I still don't think we should make the field red and show an "error" message.  that tells the user that something is broken on this page that must be fixed in order to continue.  If the user chooses to go over the 100 character limit, it's not really an error - it's a perfectly acceptable option, even though it may mean their title gets truncated in certain situations.

**Comment by jwirfs-brock** [comment]
@bpawlak I like your suggestion -- way better than mine.

**Comment by ghing** [comment]
@jwirfs-brock @bpawlak, I agree about using the real-time character counts.  This is what we do with the summary (I've included the screen shot of this below as a reminder to how it works).

So to synthesize how we want this implemented:
- [ ] Update the title placeholder to read "Edit your title here. Shorter is better - keep your title to 100 characters"
- [ ] Show a character counter that updates as the user types

I'm still unsure about how the character limit should be expressed to the user  We could:
- Show the current character count out of the (soft) limit, e.g. 90/100
- Show a red warning message, e.g. "Shorter is better!" as we do with the summary limit
- Show a warning message in another color so it's less alarming

**Comment by jwirfs-brock** [comment]
@geoffhing Your synthesis sounds right.

I like how we are handling it with the summary, where we have a real-time character count (just showing the absolute number of characters, not xx/100) that is in grey, and then a message that appears once it has gone over 100. I think we should try your second bullet.

So, to summarize:
- Grey character count (e.g. "83 characters") until limit is met
- Once limit is met, show character count plus message in red (e.g. "112 characters [Shorter is better!]")

**Comment by jwirfs-brock** [comment]
For some reason the screen shot isn't showing up for me, so here is what it looks like in the summary:
![screen shot 2013-07-10 at 10 54 22 am](https://f.cloud.github.com/assets/1020518/775390/aee23690-e970-11e2-863e-a3463a644fbf.png)

**Comment by bpawlak** [comment]
I like the "shorter is better" messaging rather than "character count limit met b/c, as we've discussed, it's not really a character count limit.  It's more of a suggestion...

**Comment by jwirfs-brock** [comment]
@bpawlak Agreed.

**Comment by patternleaf** [comment]
If anyone would like to review and provide feedback, 51c6095 should do what we want here. It's currently up on http://dev2.floodlightproject.org 

/cc @ghing @bpawlak @jwirfs-brock

**Comment by bpawlak** [comment]
Some notes:

1) I noticed that there are 3 different weights/colors of font used for the prompts:

![image](https://f.cloud.github.com/assets/2250519/951978/9e6324d4-03b8-11e3-9959-3223581df32d.png)

2) Is there a way to apply a negative top margin on the character counters so that when a user puts focus on the Title container, the elements don't slide down?

3) I see where we're going with the "Shorter is better" message, but what about something like the following presentation with a tooltip reading "shorter is better" if/when the user hovers over the warning?

![image](https://f.cloud.github.com/assets/2250519/952019/65a25956-03ba-11e3-896f-816c3fb71db8.png)

That way, we still have the saliency of the color change without the text sliding over to make room for the "warning" message.

**Comment by ghing** [comment]
+1 for @bpawlak's suggestion 3.

I wonder if we take this approach, if it would also help to  have a color change to a "warning" color at 80% or 90% (or some other configurable percentage) of the character limit.

**Comment by bpawlak** [comment]
Minor concern there is that the color change seems more gradual and therefore not as noticeable when it fires...

**Comment by ghing** [comment]
@bpawlak That makes sense. The character count alter is a common enough idiom that users should "get it" even with a one step color change.

**Comment by patternleaf** [comment]
@bpawlak 

> I noticed that there are 3 different weights/colors of font used for the prompts

The different weight of the title makes sense to me. Yes/no? I'll try to reconcile color difference. Which browser were you using? The difference doesn't seem so stark in Chrome for Mac.

> Is there a way to apply a negative top margin on the character counters so that when a user puts focus on the Title container, the elements don't slide down?

OK.

> I see where we're going with the "Shorter is better" message, but what about something like the following presentation with a tooltip reading "shorter is better" if/when the user hovers over the warning?

OK.

Re: colors. My only thought is that red is generally "error, stop, people are dying!" whereas this is "you might want to reconsider". I might expect the red to correspond with my having broken something, and I would hope that if this were the case, the app would prevent me from doing it—ie, stop accepting character input—rather than let me do it and tell me I'm wrong. So orange or yellow kind of does make more sense to me. Yes/no?

**Comment by bpawlak** [comment]
I get that the placeholder text matches the resulting font style of the actual text, but I guess I'm questioning a bit why we are using different weights/sizes in the first place...

As for colors, I agree.  Red usually means error.  Common conventions that I've seen have been red = error, yellow = warning, green = success, blue = informational

**Comment by patternleaf** [comment]
> I'm questioning a bit why we are using different weights/sizes in the first place...

Yeah. We don't have a lot of consistency around this stuff. I'm happy to lose the weight.

> As for colors, I agree.

OK.

**Comment by patternleaf** [comment]
@ghing @bpawlak @jwirfs-brock @tekhneco 

In order to use some newer API on our tooltip library [tooltipster](http://calebjacob.com/tooltipster), I updated to the latest version and its default theme is slightly different. I think it's actually a little more legible. Is everyone on board with this new theme, or @ghing is there another reason not to upgrade?

Note that the tooltip is actually opaque, but the screencap caught it just as it was starting to fade ...

![screenshot 8 13 13 2 46 pm](https://f.cloud.github.com/assets/73439/957866/c879dcd0-0459-11e3-84ca-54904ea0aafa.jpeg)

**Comment by wendynorris** [comment]
Looks good to me.

**
_wendy norris http://about.me/wendynorris_
 ceo + founder :: tekhne media, inc
a digital information and media collective
720 281 9378 :: mobile

*\* http://about.me/wendynorris
*
*

**Comment by ghing** [comment]
@patternleaf, if I recall, I had tried to upgrade tooltipster in the past and ran into some errors, so I scrapped it. We use tooltipster a lot, so I'm a little reluctant to upgrade the version without having a plan to measure its potential impact.  As for the asthetics, I'm ok with the new ones.

What are your thoughts on the impact of upgrading the tooltipster version? At the very least we should test on IE8/IE9 to make sure nothing breaks (unless the library claims to support them).

**Comment by jwirfs-brock** [comment]
I like it, too.

**Comment by patternleaf** [comment]
@ghing Hm, bummer. So far this version (2.1.4) is working in IE8 though I haven't done much testing. On the doc page, there's a mention of behavior in IE9 and IE8, which implies some compatibility.

There were three pages that included tooltipster: builder, explorer, and account. Do recall the nature of the failures? Was it obvious or subtle?

**Comment by ghing** [comment]
@patternleaf I don't remember the nature of the failures. All I found was [this comment](https://github.com/PitonFoundation/atlas/issues/548#issuecomment-16141509) that says:

> The newer version of the jQuery Tooltipster plugin has a much wider API, which would let us do things like hide 
> the tooltip when the button is clicked, or update it's text as the button state changes. However, updating the library 
> seems to break styling and behavior in a number of places, and I'm not sure hunting all those instances down is 
> the best use of my time right now.

I'm all for trying to stay up-to-date with recent stable library versions, especially when the APIs let us do things we want to do.  We could do an audit of how we use the JavaScript-generated tooltips and write some tests (or at least direct more informal testing) to make sure we don't break anything critical.

**Comment by patternleaf** [comment]
OK, so 1d13177 has the above refinements and is running on dev2 at the moment. 

@ghing, this has the upgraded tooltipster in it. In my testing it seems ok in Chrome, Safari, Firefox, and IE8. However if you think it's premature to upgrade, I can take it out.

@bpawlak, the colors in the rich text editor are still slightly different—going to require a little more investigation to match that.
