### ISSUE TITLE
Homepage: truncate featured item text.

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#589]
Was decided at 75 words, though there may be some contingencies around paragraphs, etc. Assigning to @ghing to start. Geoff, assign back to me if/when appropriate.

**Comment by ghing** [comment]
I changed the title of this issue because I think we decided that we would be truncating the body for stories and projects but not news items.  Generally, I've been calling things in that slider "Featured Items". 

~~The way I want to do this is by backporting Django's [truncatewords_html](https://docs.djangoproject.com/en/1.4/ref/templates/builtins/?from=olddocs#truncatewords-html) tag so we can use it under Django 1.3 and 1.4 and then use it in the `storybase/featured_object.html` template.~~

_Update: There's no need to backport `truncatewords_html`. This is in Django 1.3.  I was getting it confused with `truncatechars`._

My reasons for this approach are:
1. It should happen on the server-side because there's a clear and generally-used approach for this via the `truncatewords_html` filter.  There are ways we could do this in JavaScript, but it seems like it would add overhead and be more ad-hoc.
2. This should happen at the template layer server-side because it's purely presentational.  The models shouldn't be worried about the display length of their summaries.
