### ISSUE TITLE
Users shouldn't have to agree to legaliese every time they publish a story

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#590]
Currently, every time a user publishes a story, they have to agree to some legalese:

>    I have the necessary ownership/rights/permissions to legally distribute the content in this story.
>       The content in this story doesn’t violate copyright law or infringe on a third party’s trademark, trade secret, proprietary data or patent.
>        I have properly cited or credited any content that I did not create myself.
>        If this story has any photos or videos of children (under 18), I have obtained the proper parent or guardian release forms.
> 
> ```
>    Note: You can download a sample release form as a Google doc or Word doc. For more information about using photos or videos of people in your Floodlight stories, visit our Resources page.
> ```
> 
>    I participate in Floodlight’s cooperative distribution by publishing my story under a Creative Commons license. This means that I remain the owner of this story, but that my content can be featured on the site and redistributed by others. Learn more about Creative Commons.

This seems intimidating and a pain to have to do all the time.   Also, since we will soon have default values for license and featured images, the user will be able to just click "Publish" and their story will be live.  The publish step could then be reoriented around refining the story for publication (selecting image, license, maybe even title and summary) rather than as a gatekeeper step.

I thought of two ways to remove this text:
1. Include it in the general site terms of service that users agree to when they register.  That way users agree to it once when they register and don't have to deal with it again.  This is my preferred option as I think it's consistent with how other sites work.  You don't have to agree to anything before you post to Wordpress, Blogger, Twitter or Facebook
2. Show it to users the first time they publish a story, then store the fact that they've agreed to it with their profile information and then don't show the legal information as part of the publishing step for subsequent stories.

**Comment by jwirfs-brock** [comment]
Legally speaking, they don't have to agree to it every time. This is all
already covered in the terms of service they agree to when they sign up for
the site. We decided to have them check it every time to make sure users
stop and pause and actually pay attention to things like sharing images of
minors and using content that others have created. If it isn't having that
effect (i.e., people are just checking boxes without reading it), then
there's no point in making it a mandatory checkbox.

I suggest that we have a reminder text that is lighter in tone and shorter.
It's not a box they have to check, but a, "Hey, did you remember that you
need to..." message with a bullet point list of the main points. I can put
together some recommended copy.

**Comment by jwirfs-brock** [comment]
Also, just a note that our user-base tends to be an interesting combination
of a) hyper-aware about sharing and its implications, and b)
not-technically savvy, thus not used to posting content online frequently,
which means we need to pay attention to and address these issued more
directly than Wordpress or Blogger does. In our interactions with users,
we've had lots of questions about protecting images of children, copyright
concerns, etc. I think it's our responsibility to make sure that our users
are informed so that they can do everything "right" without inadvertently
breaking a copyright law of some sort.

**Comment by jwirfs-brock** [comment]
But I do agree that, as it is now, it's too intimidating!

**Comment by jwirfs-brock** [comment]
@ghing I recommend that we remove the check boxes and replace them with this updated copy:

https://docs.google.com/document/d/1AX2hXPKbYNlgvenqOUqrIwQ3WbOMwMjeUqhrFIBhh3Y/edit

**Comment by jwirfs-brock** [comment]
@ghing Because we've taken out the part about Creative Commons in the legal agreement, I suggest that we add this in under "Select a license":

All Floodlight stories will be published with a [Creative Commons](http://creativecommons.org/) license. Find out more about [why we decided to use Creative Commons](http://floodlightproject.org/en/policies/#community-values) and [how to choose a license](http://floodlightproject.org/en/policies/#using-creative-commons).

**Comment by ghing** [comment]
@jwirfs-brock What should the title of this step in the publish workflow be? Currently it's "Accept the legal agreement", but it seems like something else might be better given the changes.

**Comment by jwirfs-brock** [comment]
@ghing Because there is no user action required, it wouldn't need to be a "step" per se (it's more of a reminder). I think it's OK to just have that text directly under the header that says, "Publish and Share Your Story." Then select a license would become step 1, select a featured image would be step 2, and publish would be step 3.

**Comment by ghing** [comment]
This is live now on dev, @jwirfs-brock, please take a look at this and let me know what you think.

**Comment by jwirfs-brock** [comment]
This looks good.

The only part that's a little clunky is the select featured image step. Is
there a way to, if the story includes an image asset, have that be set as
the default? I tried it out with a story that had an image asset, and it
still showed "current image" as the generic image (chat bubble icon).

**Comment by ghing** [comment]
@jwirfs-brock Does the legal information look ok?  If so, close this issue and I'll address the default image behavior over at #515. I think it should show the first image asset included in the story rather than the default because that's actually what will happen.  I had forgotten that was the behavior when retrieving the story on the front end.

**Comment by jwirfs-brock** [comment]
Looks good.
