### ISSUE TITLE
Rethinking the connected stories format

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#602]
The connected story builder is a bit limited right now. We haven't really had users play with it, but I fear that it's too clunky to even try. I raised one aspect of this in issue #601, but there are others.
- it may not always make sense to have a photovoice as the connected story
- the title and byline are too much
- should we simplify the publish/share process?

I think we are starting to see some potential applications for connected stories in terms groups/projects that could use them, but the tool itself isn't quite ready for them.

**Comment by ghing** [comment]
I guess the connected story feature should be driven by the applications that users want.

One path to implementation could be:
1. Implement open projects
2. Making a story a seed story just creates an open project for that story behind the scenes.
3. Connected stories are related to the seed story by being added to the open project.  This could happen independent of a special connected builder, so non-Photovoice stories could be connected.
4. Reimplement the connected builder to make it even more simple.

Regarding the specific builder issues you raised:
- I'm not sure how to keep the connected builder simple, while allowing different story types.
- We can easily get rid of the title and byline, but I kind of feel like we should at least have a title. Without it, it's more difficult to visually highlight stories when they're displayed.
- Since none of the publish/share actions are required any more, I think we should get rid of the publish/share step.

**Comment by jwirfs-brock** [comment]
I like your suggestion about using open projects as a way to improve the
connected stories implementation. I agree that it's difficult (if not
impossible) to keep it both simple and completely flexible/adjustable for
different story types. Maybe a good way to go forward with this is to
identify a few test cases based on the user-interactions we've been having.
One is the six-word memoir concept. Another might be the alleyways project
Westwood residents are working on. From there, we can see how we actually
want the connected stories to work and how they might be structured.

**Comment by ghing** [comment]
I think I understand better now - so you're imagining having multiple, simple, single-section templates to choose from.  That makes more sense, but it seems like it still makes the most sense to have one template type for each seed story (but they wouldn't have to all be PhotoVoice).  In that case, the creator of the seed story would choose the template type, not the user creating the connected story.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
