### ISSUE TITLE
Title text should be cleared when user clicks into it

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#616]
Right now, when I click into a title field, the cursor is placed at the end, instead of clearing out the title.  So users potentially end up with titles such as "Element 3Making a Difference in Your Community"

**Comment by patternleaf** [comment]
it appears that this is a result of the templates providing default values for certain fields. for example, the default value of the title field in an Image and Text section is "Image and Text". i think this is coming out of the template definition itself. this _should_ be put into the placeholder attribute of the input for that field, but not the value attribute. 

i'm not 100% sure how to distinguish between the default title when a template is freshly loaded versus a user-edited title.

@ghing any thoughts about direction for this?

**Comment by ghing** [comment]
@patternleaf, you're right that the title gets copied over to the story when it's initialized from the template. But, before we get into dealing with that ...

Personally, I don't think this is really an issue.  What happens when the user clicks into the text input is that the cursor goes wherever the user clicks.  The behavior reported in the issue is because the input is often much longer than the title, so clicking into the empty space to the right of the text will place the cursor at the end of the text in the input.  If you click at the beginning, the cursor is at the beginning of the text.  If you click in the middle, it goes in the middle.  It's just more likely that you'll click at the end. The behavior when the user clicks into a text input is consistent with editing an existing value in a text input across the web. I feel like if the user previews the story, they should see the weirdness and go back and fix it. 

So, is the problem really with how the text input is behaving, or that the user doesn't realize that the value in the input _IS_ the title.  Perhaps there's some confusion because the text in the inactive input is lighter, suggesting a placeholder behavior? 

So, the fundamental question that we have is, do we want to set initial values for section titles based on the template? Or set them to empty strings? I don't think we should change the behavior of the text input to act like a placeholder when the section title still matches that of the template and act like a normal input at other times.

If we don't want to set the default value of new sections to be an empty string, but do want to offer a suggestion from the template (as a placeholder), here's what we need to think about ...

The new section titles are copied from the template section titles in `BuilderView.initializeStoryFromTemplate`, which calls `Story.fromTemplate` to copy the section information over to the new story.  This happens right after the user selects a template (and the template story structure is fetched from the server).  After that, the code pretty much forgets about the template story.  

So, one obvious solution would be to set the `title` of the new section to an empty string in `Story.fromTemplate`, then use a default placeholder.
 and set a separate attribute, say `suggestedTitle` to the title from the template section.  Then you could render the suggestion as a placeholder in the form field.  

The problem is when the user exits the builder and returns.  At this point, the builder no longer loads the template story, so we don't have a way to get the template section titles.  I can think two technical ways to handle this:
- Don't worry about it.  Just a show a default placeholder on subsequent opens in the builder.
- Have the API resource return the template section title as a read-only field (again, something like `suggestedTitle`) when bootstrapping the builder on subsequent loads.  This seems ok, other than (probably) some additional database calls to join in the title from the template.

**Comment by ghing** [comment]
In a chat with @patternleaf, he did a good job of phrasing the fundamental issue as section titles having default values while most of the other inputs have no default values (but do have placeholders).

**Comment by patternleaf** [comment]
so i'm having some trouble getting this to do quite the right thing, even in the scenario wherein we don't try to recover  the story template's placeholder title/suggested title on load. summary of behavior:
- when creating a new story from a template, the first section title gets its template-defined placeholder
- when creating a new section, that section gets a generic 'Section Title' placeholder
- when loading a saved story in which a section lacks a title, that section isn't getting _any_ placeholder at the moment.

that last could be handled by the handlebars template, but perhaps we'd prefer it to live in the view?

also i updated the section list view: when a section has no title it displays 'Untitled Section' rather than 'New Section' ... seemed a little more appropriate. however, this is also handled in the handlebars template rather than in the view code.

**Comment by patternleaf** [comment]
ps, the above is in commit 64cd08b.

**Comment by ghing** [comment]
@patternleaf, my thinking in terms of putting UI strings in the template as opposed to the view was to have them be in the template as much as possible.  My thought was that for quick textual changes, being able to change everything in one place, and in a place where the context is more clear, would be the way to go.  I figured that more people understand editing HTML, even with some template markup, and it's clearer to edit these strings in HTML than in JavaScript code.

That said, it's not always possible to put it in the template, and I'm sure there's places where we don't do this consistently, so I'm open to discussing this, I just wanted to clarify my intent in making things work the way they do now.

**Comment by patternleaf** [comment]
@ghing that makes sense. the uncertainty i expressed above was more about putting _logic_ into the template. for example, [in this line](https://github.com/PitonFoundation/atlas/commit/64cd08b#L0R104) of commit 64cd08b, the section list widget gets an "Untitled Section" label if the section title is empty.

``` html
<div class="title">{{#if title }}{{ title }}{{else}}{{gettext "Untitled Section"}}{{/if}}</div>
```

so in the issue i mentioned above

> when loading a saved story in which a section lacks a title, that section isn't getting _any_ placeholder at the moment.

one solution would be to change

``` html
<input class="section-title" name="title" value="{{title}}" placeholder="{{title_placeholder}}"/>
```

to

``` html
<input class="section-title" name="title" value="{{title}}" placeholder="{{#if title_placeholder}}{{title_placeholder}}{{else}}{{gettext "Section Title}}{{/if}"/> 
```

in which case we'd probably want the generic placeholder behavior to be entirely in the template instead of the view.

**Comment by ghing** [comment]
I also question putting logic in the template as well. I also don't like hard-coding strings in under-the-hood code either.

I think that this might be a case where the best way to go would be to write a [handlebars helper](http://handlebarsjs.com/#helpers) that works like the [default template filter in Django](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#default). So, its syntax would be something like:

```
<input class="section-title" name="title" value="{{title}}" placeholder="{{{default title_placeholder "Section Title"}}}"/> 
```

So, it allows us to keep our UI strings in the template while avoiding the ugliness and verbosity of if/else tags in the template.

I don't know if it's better to try to stay consistent with the 2 template languages and call this helper `default` or if there's a name that would be more readable.

**Comment by patternleaf** [comment]
ok, i think we're good to go with this one.
