### ISSUE TITLE
Section titles in TOC when user doesn't specify a custom title 

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#619]
I think we need to create an issue for how we'll handle sections without titles, both in the story viewer and table of contents. Check the table of contents for this story: http://deploy.atlas.terrorware.com/stories/charting-a-new-course-in-sheridan/ ... see "Section 2" "Section 6" etc...

TODO:
- Generate a list of sections without titles or with default titles
- Reach out to users to find out their intention in leaving out section titles
- Define Jordan's desired behavior for how she'd like her titleless sections to appear in the ToC.

**Comment by ghing** [comment]
I feel like to do a good job of handling sections without titles, we need to know why users have sections without section titles.  Is it because they see the title-less section as a continuation of the previous section, but the layout didn't give them enough buckets to put their content? Did they just forget to set a title? If it's helpful, I can get a list of all the sections in published stories that don't have titles if someone wants to reach out to users and ask them about it, or try to interpret the intention behind the section-less sections ourselves?

**Comment by jwirfs-brock** [comment]
@ghing A list of section-less titles would be great. I think what we'd
actually want is a) title-less sections, and b) sections with the default
(i.e., not changed from the template). I'm happy to reach out to users and
ask them about it.

Many of them will be from my stories. When I don't use section titles, it's
because a) it's a continuation of the previous section, or b) it's a case
where a section title seemed overkill, and a story title was fine (like in
the photo voice template it often seems redundant/unnecessary).

I think in the case of our users, a lot of the time it's that they forgot
to put in a section title, or didn't realize that they even could/should,
so they don't change it from the default. But it could also be that they
don't really think section titles are necessary. I'm in favor of asking to
find out.

**Comment by jwirfs-brock** [comment]
Should we tackle this as two cases?
1) Users leave the default section title
2) Users leave a section title blank.

**Comment by ghing** [comment]
Yeah, I think these are two different cases, specifically because the check for each is different.

One consideration is that it's expensive to do the check if the users have left the default section title in the viewer.  If we want to catch this and warn users, I'd wire it up in the builder somehow (and treat it as a separate issue).  

Checking if the section title is blank in the viewer is cheap and easy.  Note that the current behavior is that we just give the section a label relative to it's order (e.g. "Section 1, Section 2") in the table of contents so there's something to click on.

**Comment by bpawlak** [comment]
Any merit to simply having the default section titles be UI only?  That is, there's no default name for the section - it's just blank.  Yes, the UI has "Enter a title" or something but as soon as they click into the title, we remove the helper text and let them actually type something.  If they don't type anything, we shouldn't have that section's title be "Enter a title"  Not sure if I'm explaining correctly, but you see a similar behavior in gmail when you go to compose an email.  The "Recipients" and "Subjects" text both disappear when I type something.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
