### ISSUE TITLE
When you toggle a story's "featured on homepage" status, it changes the last edited date

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#625]
I'm not sure if there's a way to fix this, but right now, when you toggle a story's "featured on homepage" status in the Django admin, it considers that a story edit and updates the last edited date. 

The consequence of this is that the story then goes to the top of the recent stories list on the homepage. (An example is (OpenWorld Learning Opens up a World of Opportunity for Students)[http://www.floodlightproject.org/en/stories/openworldlearning-opens-up-a-world-of-oportunity-f/], which I just removed from the homepage slider. It is now at the top of the recent stories list. Oddly, this did not seem to happen for the story that I **added** to the homepage slider (http://www.floodlightproject.org/en/stories/food-for-thought-volunteering-at-the-colorado-food/). That is, when I toggled this story's featured on homepage status from off to on, it did not then go to the top of the recent stories list.

**Comment by ghing** [comment]
This issue needs a bit of testing and analysis, which is why I'm giving it 4 points, even though the implementation won't take a lot of code. Especially curious @jwirfs-brock's report that toggling the `on_homepage` field (which appears as "featured on homepage" in the Django admin) from off to on doesn't change the sorting order of the latest stories, but toggling it from on to off does.  Off the top of my head, I'm not sure why this is happening.

On face, it seems like we could just sort by the `published` date field (which doesn't change when the `on_homepage` flag is edited).  However, in a previous issue @jwirfs-brock asked that the latest stories order be updated when a new connected story is added to a seed story.

One possible solution would be to add a `sort_date` field that would be equal the `published` field of the story or the `published` field of a seed story's latest connected story.  We would then use a South data migration to set this retroactively for all the existing stories.

I'm not sure if it's a good idea to update the `last_edited` field so it's only updated when some fields change and not others.  First, I'm worried the schema migration to unwire this might be messy (I'm not sure of the auto_update flag is implemented at the database level or with signals or something else) as would the logic for selecting when to update the field.

**Comment by ghing** [comment]
@jwirfs-brock I'm assigning this to you so you can comment and describe:
1. What you would like the latest stories sorting to be based on (when the story was first edited, when it was first published, something else entirely) and how connected stories should factor into this?
2. Are there any other lists on the site (not just of stories, but also possibly of projects or organizations), where you'd like to see the sorting behavior changed. If so, how would it be different?

**Comment by jwirfs-brock** [comment]
@ghing I suggest that...
1. The latest stories (list on homepage) is ordered by first published date. Seed stories should be ordered by the publish date of the most recently added connected story. (That is, a seed story with no connected stories should be treated like any other story. But, once it has connected stories added to it, when there's a new addition, that updates its priority.)
2.  Right  now, organizations are alphabetical. Let's keep it that way.
3. I'm not sure how the ordering happens for projects right  now. I believe it's last edited? That's fine. But for projects, as well as stories, toggling featured on homepage status shouldn't update the last edited date.

**Comment by ghing** [comment]
Projects are currently sorted by the last edited date.  Is there a reason in your proposal for projects being sorted by the last edited date rather than the published date like stories?

Also, I'm wondering if you mean _the ordering of stories should not change when the on homepage status is toggled_ or _the last edited date/timestamp should not change when the on homepage status is toggled_.

**Comment by ghing** [comment]
A technical note: If the behavior we want is to update the last edited timestamp every time a story is changed, the general consensus seems to be that I shouldn't use `auto_now` and should instead override the `save` method on the model.

**Comment by jwirfs-brock** [comment]
Note: I just "untoggled" these stories from the homepage slider, and now they are at the top of the "Latest Stories" list on the homepage:
http://floodlightproject.org/en/stories/food-for-thought-volunteering-at-the-colorado-food/
http://floodlightproject.org/en/stories/groundwork-on-planting-peace-in-whittier/

**Comment by ghing** [comment]
I think the way to go is to add a `sort_weight` field that defaults to an integer representation of the published date and gets bumped each time a connected story is added.  Having the sort value be an integer field instead of a date allows for future flexibility if we want to have the sort order be a combination of variables.
