### ISSUE TITLE
User reported error while trying to publish a connected story

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#628]
The connected story is ["Today, the digital divide is closing."](http://www.floodlightproject.org/en/stories/six-word-memoirs/viewer/#connected-stories/07f4db029c6946b79d9ba65f589bb3a3) and the seed story is ["Six-Word Memoirs"](http://www.floodlightproject.org/en/stories/six-word-memoirs/).

I'm not sure what caused the error, but here is what the user reported:
"I tried to edit then post my 6 word story and I could not get into edit.....I back tracked and figured out how to publish it. I should have done a print screen to send you. My instinctive steps lead me to an error message telling me something about cache  -  which when I clicked on send me to Wikipedia."

**Comment by ghing** [comment]
From this it sounds like the user couldn't get back into the builder.  My guess is that maybe they had a stale version of the builder JavaScript after the last update.  The fact that they were eventually able to publish makes me think this is the case.  With the fix for #623, now in production, we should be able to get more granular, and automatic reports when users run into these unexpected errors.

If we implement #624, we can eliminate stale JavaScript issues moving forward.

I'm going to close this because there's not really enough information in the error report to further identify the issue.
