### ISSUE TITLE
Using seeing an error message after clicking on email authentication link during sign up process

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#675]
Here's what happened:
- A user signed up via email.
- Then clicked on the emailed authentication link.
- Then was taken to an error message saying there was a problem with the authentication.
- Was nonetheless authenticated (i.e., when left site and came back, he was logged in).

So essentially, the authentication link is working, but sending the user to an error message anyway.

**Comment by ghing** [comment]
I wasn't able to replicate this doing some quick testing.  

## Steps

I did this on staging, but it has the same software stack and a fairly recent version of the production data.  I can't think of any reason the outcomes should differ from staging to production.
1. Deleted the account for my test e-mail address.  This also deleted the associated registration profile model instance.
2. Made sure I was logged out of floodlight
3. Visited the sign in page
4. Clicked the `Don't have an account? Join now.` link
5. Submitted out the sign-in form and received the confirmation message in the browser
6. Clicked on the confirmation link that was sent to my e-mail address

## Result

Following the confirmation link caused me to be signed in and taken to the newly-created user's "My Account" page.

This is the expected result.

## Additional notes

For the user in question, the registration profile model instance showed a status of `ALREADY_ACTIVATED`, confirming the report by @jwirfs-brock report that the user registration authentication was successful despite the user receiving the error message.

Since this is confusing but not preventing usage, and I couldn't replicate it, I would say we just try to track this and do further testing if we get more reports.

**Comment by jwirfs-brock** [comment]
I couldn't replicate it either. But I have had reports of this before from
other users. I think we just don't know what exactly is causing it (there
could be something that they are doing that we aren't aware of/are missing).

**Comment by ghing** [comment]
I did notice that if I visited the activation link a second time (after a successful activation), I saw the error message. 

So, this could be a case of multitasking users clicking on the link (and successfully activating their account), then forgetting that they did this and clicking on it again and getting the error message.  Because they've already activated their account, they're able to use their account normally.

**Comment by jwirfs-brock** [comment]
Hmm, yes it could be that he clicked on the link more than once.

**Comment by ghing** [comment]
If the scenario described in my previous comment is what's causing this for most of the users, the fix would be to show a specific error message for the case where the user has already activated the account instead of the default behavior of the registration framework, which is to use a single error template for all errors.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
