### ISSUE TITLE
Issues with Storify embed in viewer

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#693]
I've noticed that the Storify slideshow I posted about the Redline story-raising [http://floodlightproject.org/en/stories/story/] keeps breaking. It'll work for a few days and then appears to deprecate resulting in only the first slide visible. I've reposted the slideshow script a couple of times and am still having the problem.

So, I re-posted the story with the traditional Storify stream to see if it's merely a sideshow problem. The stream will not display beyond the first tweet in the story modal window (in Firefox) but it will display in full in a new browser window (also Firefox).

Storify is buggy as hell, so I'm not sure if it's their issue or a Floodlight one. I know the co-founders and would be happy to make an introduction if you think that might help get to the bottom of the conflict between Django and the Storify embed script.

**Comment by ghing** [comment]
Updated issue title for clarity.

**Comment by ghing** [comment]
@tekhneco, can you copy and paste the embed codes for both the slideshow and traditional stream into this issue so I can do some testing?

The traditional Storify stream embed (which is what I assume is currently embedded in the story) works ok for me in Chrome.  

I was able to replicate the issue that you reported in Firefox.  I suspect this is because the Storify embed script sets the height of the iframe based on the window height.  In the case of the modal popup, this is a lot shorter.  The container element sets it's height based on the initial height of the iframe and ends up cropping the iframe element.

If I have the embed codes to play with I can get a more clear idea of what's going on with this and whether we can fix this on our end or report it as an upstream issue.

**Comment by wendynorris** [comment]
Here's the regular embed script (without SEO): 

`<script src="//storify.com/FloodlightStory/near-northeast-denver-story-raising.js"></script><noscript>[<a href="//storify.com/FloodlightStory/near-northeast-denver-story-raising" target="_blank">View the story "Near Northeast Denver Story-Raising" on Storify</a>]</noscript>`

Here's the slideshow embed script (without SEO): 

`<script src="//storify.com/FloodlightStory/near-northeast-denver-story-raising.js?template=slideshow"></script><noscript>[<a href="//storify.com/FloodlightStory/near-northeast-denver-story-raising" target="_blank">View the story "Near Northeast Denver Story-Raising" on Storify</a>]</noscript>`
