### ISSUE TITLE
Story summary should appear on topic map for spider view

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#70]
For the spider view, the story summary should appear on the topic map page. It should go in the grey story info bar at the top of the story viewer window (see screen shot for placement: http://a.yfrog.com/img152/7656/lnk.png).

**Comment by ghing** [comment]
I'm imagining that a lot of summaries might be too long to fit in that space, especially since it's also used for the current section subtitle.  Do only want the summary to show up when the topic map appears?  How do you want to handle really long summaries?  Have you tried mocking this up with a longer summary?

**Comment by ghing** [comment]
Update @jwirfs-brock and I decided to put this in the body of the story viewer as documented in the acceptance tests.

**Comment by ghing** [comment]
Closed by 12a120f4ab3d8693bbc999d18d92d0f3d7b297ae
