### ISSUE TITLE
Editing Summary v. editing Byline -- placeholder text behaves differently

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#722]
When you edit the Summary, the placeholder text stays there (you have to highlight it and then delete it), whereas when you edit the Byline, the placeholder text disappears as soon as you start typing.

Should we resolve this inconsistency? My preferred behavior would be to see the placeholder text in the Summary also disappear when you start typing.

**Comment by ghing** [comment]
@jwirfs-brock +1 for making the summary text a placeholder. I think the original idea was that the template text would be a starting point for the user editing their own summary, which is why it's real text.  However, that's not how its used now, so I think it makes sense to just make it a placeholder.

**Comment by ghing** [comment]
@jwirfs-brock, the summary of a new story is copied over from the template story.  That's why it's real text instead of a placeholder. Do we want to use the summary text from the template story for the placeholder instead of the default placeholder "Click to edit the summary".  If it's the latter, you can just remove the summary from the template stories (in the Django admin) and the default placeholder will be used.

Not to myself: The path to do something different is this:  remove the copying of the summary field in the Story.fromTemplate method. Make a new Story.placeholdersFromTemplate method that sets and "summary_placeholder"

**Comment by ghing** [comment]
Assigning to @jwirfs-brock for an answer to [this question](https://github.com/PitonFoundation/atlas/issues/722#issuecomment-20234851)

**Comment by jwirfs-brock** [comment]
@ghing I like it better if we can have a different summary for each template. Right now, it looks like the Sandbox and Data Story templates have specific summary text -- the others are using the default. I'll update the summary text for PhotoVoice and Explainer.

Related to that, if it's trivial to do, is there a way to add a filter to the story list in the admin view so that you can just view stories that are a template? I believe that feature exists on the admin view for sections, but not for stories.

If it's not simple/quick to do, don't worry about it -- I can find the stories the templates were created from by searching.

**Comment by ghing** [comment]
@jwirfs-brock Ok. I'll implement this so we can have per-template summary placeholders. Implementing it this way will also help get us toward eliminating the default "Untitled Section" titles in the section list.

It's easy to add that filter in the admin.  Can you open a separate issue for it though so it's easy for me to track?
