### ISSUE TITLE
Hard to find data associated with story

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#733]
From sandbox test story on dev.floodlight: 
http://dev.floodlightproject.org/stories/375044e162aa40968ff239a6d52b2aec

Uploaded data set does not appear in published story. 

Still todo:
- [x] Decide on placement of "Get the Data" button on story detail page

**Comment by ghing** [comment]
I'm seeing the uploaded data set at http://dev.floodlightproject.org/stories/375044e162aa40968ff239a6d52b2aec/.  You have to scroll down to the story metadata section to see it:

![screenshot from 2013-04-30 14 01 06](https://f.cloud.github.com/assets/110420/445931/6a22a60a-b1c8-11e2-8489-ef229b92aad2.png)

I'm thinking that this presentation could definitely be a little better. @tekhneco, can you confirm that the issue is that you just missed the data set and I'll update this issue to reflect that the problem is not that the data set is not associated with the story, but that the relationship is not prominent at all.

**Comment by wendynorris** [comment]
Agreed that the presentation of the data source needs to be more prominent and more relevant to where it is located. I would never expect to see the link in the story masthead.

**Comment by ghing** [comment]
@tekhneco, feel free to add any suggestions about better placement. I'll update the issue title to reflect the issue being bad placement rather than not listed.

**Comment by jwirfs-brock** [comment]
Some ideas for this:
- We could have a "this story has data" icon that appears next to the story title (when it is displayed on the explore page, on the homepage, etc.). I'm not sure whether it makes sense to have this icon by a link to the "Data Sets" list (just as an anchor on the story detail page)...that could be a bad idea.
- On the story detail page, we could make the "Data Sets" list more prominent. Even a bold header and a space/line break between the "Topics" line above would make it stand out more.
- Also, a heading more active than "Data Sets" might pull readers in more. I like "Get the Data."

Other thoughts?

**Comment by jwirfs-brock** [comment]
Another option for making the data sets more prominent is that, instead of listing them below the topics/tags list, we could put them under the summary (possibly right below the "view story" button?).

As I said earlier, even just a more enticing header that is bolded might do the trick (wherever it's placed):

**Get the Data**
My data set

**Comment by ghing** [comment]
I'm worried about pushing the story metadata even lower "below the fold".

Two more ideas:
- "Get the Data" as a [drop-down button](http://twitter.github.io/bootstrap/components.html#buttonDropdowns) that lives next to the "View Story" button

![screenshot from 2013-06-06 09 36 04](https://f.cloud.github.com/assets/110420/618555/63ca6ce6-ceb7-11e2-967f-caa97bee7202.png)
- "Get the Data" as a banner a-la [GitHub Ribbons](http://twitter.github.io/bootstrap/components.html#buttonDropdowns)

![screenshot from 2013-06-06 09 41 49](https://f.cloud.github.com/assets/110420/618566/9b2f3360-ceb7-11e2-9fd9-7ca4f81c29a7.png)

**Comment by wendynorris** [comment]
I really like the concept of a "Get the Data" button placed next to "View Story."
