### ISSUE TITLE
Comment feature needs to be easier -- maybe enable commenting without login (or via Facebook plugin)?

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#739]
This was a suggestion that came up with a meeting at the Denver Foundation. They think it would be easier for people to comment on stories if they could comment using Facebook (something like the Facebook social plugin: http://developers.facebook.com/docs/plugins/).

**Comment by ghing** [comment]
Brain dump of questions:
- Is the goal more comments, or to encourage other interactions that could be implemented via comments?
- Do people not comment because it requires a Floodlight account, or because of the placement of the comment form, or because the stories aren't compelling enough to elicit a comment?

I'd prefer Disqus over the Facebook commenting system. It's still easy, but offers a number of social login options beyond just Facebook.

**Comment by mgrayinnovation** [comment]
Commenting eliminated during 2015 pivot.
