### ISSUE TITLE
Embed widget link behavior seems inconsistent, doesn't set user expectations

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#744]
In the current embed widget, there are 3 links.  This is their behavior:
- Featured image -> story detail page
- Title -> Opens story viewer in new tab (or window depending on user's browser preferences)
- "View this story on Floodlight" -> story detail page

While I think it makes sense to have both links that open the viewer and ones that link to the detail page, I don't know if the current behavior is what's expected based on the text.

This is somewhat related to #741

**Comment by jwirfs-brock** [comment]
@ghing Do you have suggestions for how we could name the links?

"Read this story" seems like an obvious one for opening it up in the viewer. What we would call the link to the story detail page? "Find out more..."? I am not sure if, as a reader, I would undertand the distinction.

It seems we should also have a link to the Floodlight homepage, or the Floodlight explore page, so that readers can view other Floodlight stories.

**Comment by jwirfs-brock** [comment]
Our new widget design should fix this problem. Putting this in the embed widget milestone for reference purposes...
