### ISSUE TITLE
Thumbnails for HTML assets

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#771]
We don't have a way to display thumbnail URLs for non-image assets.  Right now, in the asset sidebar, we fall back to icons, but this makes it hard to distinguish assets if a user has multiple unused assets of the same type.  However, this is a non-trivial problem since we have to figure out a way to render HTML to an image on the backend.

http://jeanphix.me/Ghost.py/ or https://github.com/niwibe/phantompy might be a good start.

**Comment by ghing** [comment]
Assigning to @jwirfs-brock for triage.

**Comment by jwirfs-brock** [comment]
@ghing Just confirming that when you said "non-image assets" that just referring to embed code and not things like Soundcloud and YouTube, right?

**Comment by jwirfs-brock** [comment]
Right now I'm actually not seeing an icon. When I deleted a chart asset (created with an iframe) in Firefox, I am just seeing an empty asset drawer:

http://floodlightproject.org/en/build/b816eddadd854cfaa163ce95151dc2c9/

**Comment by jwirfs-brock** [comment]
To help think this through, I'm going to restate this problem to: Users can't distinguish between assets of same type in the asset drawer because they have the same icon and don't have any other identifying features.

Some ideas of how we might address this (all these ideas are bad, but I'm kind of at a loss here...):
- Require a title for an html asset (I don't like this very much, but it would simplify things because then we could use the title to label the asset)
- Show the beginning of the code snippet (I don't like this either, because if you are using, say, several iframe or script tags, the beginning of the code snippets would look the same
- Show some kind of time stamp so you can at least see which asset you added first/second? (I can never figure out whether the most recently deleted assets go to the top of the asset drawer, or to the bottom, or whether it's ordered by when the asset was created, etc.)

**Comment by ghing** [comment]
A few replies to @jwirfs-brock ...

> @ghing Just confirming that when you said "non-image assets" that just referring to embed code and not things like Soundcloud and YouTube, right?

Right. I'm talking about things with HTML embed codes. In most cases, providers that offer oEmbed provide a thumbnail version of the asset, so this is less of a problem. Also, URL-based embeds have the URL as an identifier which helps somewhat.

> Right now I'm actually not seeing an icon. When I deleted a chart asset (created with an iframe) in Firefox, I am just seeing an empty asset drawer:

There was a bug where some asset types weren't getting icons. This is fixed in the `develop` branch and will get deployed along with the #583 changes.

> Some ideas of how we might address this ... 

I think it's hard to find a good low-fi fix that actually addresses the issue.  I think we should either:
- Spend the time to see if we can generate thumbnails for these assets
- Provide a "preview" link that opens  popup that shows the rendered asset content

Obviously, these solutions aren't mutually exclusive, and as @bpawlak mentioned in another discussion thread somewhere, a preview would still be helpful for things like maps that are hard to distinguish from a thumbnail.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
