### ISSUE TITLE
Story Viewer top header scrolls off page

### ISSUE THREAD

**Issue by bpawlak** [denverfoundation/storybase#772]
When a story has a tall page (lot of content, scroll bars are needed), as the user scrolls down the page, the top header (with the story title, new window and close viewer icons, etc.) scrolls out of view.  Although this was done intentionally to deal with long story titles, I think we should re-address the issue as it seems broken.  

Can we simply add "position:absolute" to header id="header"?

**Comment by ghing** [comment]
This behavior was introduced to address #684, which is why a simple `position:absolute` or `position:fixed` doesn't work well.

We should probably fix this because as @patternleaf pointed out, when viewed in the popup, the close and open in new window icons become invisible too.

My suggestion would be to toggle the position of the header to be fixed or absolute only when the user starts scrolling.  This behavior can be seen in the [jQuery Waypoints Sticky Elements example](http://imakewebthings.com/jquery-waypoints/shortcuts/sticky-elements/) (though we can probably just implement this effect ourselves rather than using the plugin).

It might be easy enough to just assign a body class of `scrolling` once the user starts scrolling and to have a css style like:

```
body.scrolling #header {
  position: fixed;
}
```

**Comment by patternleaf** [comment]
Turns out it's not quite so simple, unfortunately, since setting the header to `position: fixed` removes it from document flow, and the story body pops up to compensate, resulting in a jumpy transition (and sometimes a nice fun infinite back-and-forth thing). The solution in 942f5a1 is to compensate via `padding-top` on the body. I put it all in JS rather than have some of the solution live in CSS and some in JS. @ghing let me know if you have other thoughts...

**Comment by ghing** [comment]
This is quick feedback having not looked at the commit. I generally prefer
(though I'm definitely not consistent about this) to toggle a class in js
and keep anything that doesn't need to be calculated dynamically in CSS.
I'm open to counter arguments. I can speak better to this when I look at
the code.

**Comment by patternleaf** [comment]
Yeah, understood. In this case we do need to fetch and store the browser-calculated height of the header element so that it can be converted into padding on the body when the header leaves document flow. I think the only thing that could be in CSS for this approach is `position:fixed` on the header, which could be toggled based, as you suggested, via a class on the body. The view in 942f5a1 has a method called setStickyHeader. It struck me as strange for it to require CSS being set elsewhere to actually function, so I made it all self-contained. _shrug_ No big deal, though.

**Comment by ghing** [comment]
This looks pretty sane. What cases have you tested this solution on?  Have you tried it with /stories/the-denver-foundation-prepares-for-the-seventh-cla/viewer/, the story that spawned #684?

**Comment by patternleaf** [comment]
Tested against sections without scrolling, sections with scrolling, initial load to a mid-story section, and yes: tested against #684; that still works. 

Are there any cases where we might find ourselves initially rendered in the middle of a section page—already scrolled? Seems unlikely, but that's one case where this code might not work so well.

**Comment by patternleaf** [comment]
Oh: and tested in FF, Chrome, Safari, and IE8.

**Comment by patternleaf** [comment]
Seems like we're good to go with this? Will send a pull request if there are no objections.

**Comment by ghing** [comment]
Yup.
