### ISSUE TITLE
Call to Action display in Story Viewer for a spider story

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#81]
The Call to Action should be displayed in the Story Viewer for a spider structure as:
1. The Call to Action text should be displayed on the left side of the Story Viewer, under the Summary, with the heading "How Can You Help?"
2. Both the Summary and the Story Viewer should have half of the left column reserved. If they don't fit, the text should be truncated and a "read more" link should be displayed. When  you click on the "read more" link, it should take you to the Summary or Call to Action rendered as a story section (i.e., text by itself in the Story Viewer).
3. In the Table of Contents list, the Summary should appear at the top of the list, with a break between it and the list of story sections. The Call to Action should appear as it does now. When you click on either link, it should take you to the Summary or Call to Action content rendered as a story section in the Story Viewer.

It should look like this: http://a.yfrog.com/img207/4205/cr1x.jpg 
(I put the T.O.C. opening down, but that was just for space -- it should still open up, obviously)

**Comment by jwirfs-brock** [comment]
Note: For the linear story, the way it is rendered now is fine.

If there is no Call to Action, then it should be hidden (i.e., not appear either on the left or in the Table of Contents). The Summary can still be limited to the top half of the left column.

**Comment by ghing** [comment]
Jordan,

Re: number 2 (above), I feel like it's better for the read more link to just unscroll the truncated text rather than having it jump to a separate rendering.

http://henrik.nyh.se/examples/truncator/ has an example of how this works.

Does this work for you, or is there a reason that you'd prefer the "read more" link to jump to viewing that content by itself, taking up all the space in the viewer window?
