### ISSUE TITLE
Create RSS feeds

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#816]
Create two RSS feeds for: 

1) all published stories 

2) all "how-to" tutorials AKA [topics=36](http://floodlightproject.org/en/explore/?topics=36)

The feed should contain the following elements: 
- title
- author 
- featured image 
- summary

**Comment by wendynorris** [comment]
@ghing 

In the MailChimp RSS-driven campaign, I can customize the script to pull/place specific post categories into the email template. 

However, I'm unsure about how "topics" work in Django. Are they simply another term for "category" or do they function differently? If it's the former, I may not need the topics=36 feed.

**Comment by ghing** [comment]
@tekhneco It looks like `category` is an [element of an RSS feed](http://www.w3schools.com/rss/rss_tag_category_item.asp) from the RSS spec rather than corresponding to an entity named "category" in any particular RSS-generating system.  

I can make our feed include Topics, Projects, Organizations and Places as `category` elements in the unified feed so that you can filter specific topics on the MailChimp side.

**Comment by wendynorris** [comment]
Great! Thanks for adding those elements. Will make the automation process
for creating the newsletter much better.

**
_wendy norris http://about.me/wendynorris_
ceo + founder :: tekhne media, inc
a digital information and media collective
720 281 9378 :: mobile

*\* http://about.me/wendynorris
*
*
