### ISSUE TITLE
Can't switch to Publish workflow step in Internet Explorer 8

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#830]
To replicate:
1. Create a new story using the sandbox template
2. Enter a title, initiating auto save
3. Click on the "Publish/Share" workflow tab

Expected behavior:

Publish/share workflow step is shown

Observed behavior:

Blank content area is shown

JavaScript console shows:

```
User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
Timestamp: Thu, 8 Aug 2013 00:00:59 UTC


Message: No such interface supported

Line: 4
Char: 5344
Code: 0
URI: http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js
```

though it seems like this error might be being shown on page load.

**Comment by ghing** [comment]
Assigning to @jwirfs-brock for triage.

**Comment by jwirfs-brock** [comment]
@ghing What exactly do you mean by triage? This seems like a pretty major issue (users can't publish from IE8), so we should probably handle it quickly. I'll take a peek at our Google Analytics and see how many users are on IE8.

**Comment by jwirfs-brock** [comment]
Looks like, since January 1, Internet Explorer has been the 4th most popular browser, accounting for 16% of all site visits. Of those, IE8 is the most popular, followed closely by IE9.

![screen shot 2013-08-08 at 8 46 39 am](https://f.cloud.github.com/assets/1020518/931262/cad6a5ec-0028-11e3-925b-9c359b8509bd.png)

![screen shot 2013-08-08 at 8 46 51 am](https://f.cloud.github.com/assets/1020518/931265/d0dadbde-0028-11e3-8522-295056f44d55.png)
