### ISSUE TITLE
Users see "problem with activation" message when creating new account, even though activation is successful

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#836]
This is a user-reported bug that has happened several times, but does not happen persistently.
- User created a new account with an email address
- User got email with activation link
- User clicked on link in email and saw the following message in the browser:

> **There was a problem with your activation**
> There was a problem activating your new account. Please check that you correctly copied and pasted the activation link from your e-mail, or if you clicked on the link, try copying and pasting it. If you're still not able to activate your account, please contact help@floodlightproject.org.
- At this point, the user sent us an email
- I looked at the admin, and the user's account had been successfully activated
- User was successfully able to log in

**Comment by jwirfs-brock** [comment]
@ghing said:

> My thought about what's happening here is that the user is opening the link multiple times.  The first time, confirms the activation, but they don't see it because of lots of browser tabs, windows, something else.  The second (and subsequent) times, they're seeing the error message.  Can you do a little testing and confirm that the user sees the reported error message when they click the activation link more than once?

**Comment by jwirfs-brock** [comment]
Sure, I'll see what I can find out.

If it is a matter of opening the link multiple times, then shouldn't we have it just redirect to the login page on subsequent visits, instead of displaying an error message?

**Comment by jwirfs-brock** [comment]
@ghing I confirmed that if you click on the activation link multiple times, you see the error message after the first time.

**Comment by jwirfs-brock** [comment]
So, the solution seems to be that we need to change the text for that page/the error message. Do we still need to keep that error message at all? Have we observed instances where the activation hasn't worked? 

Maybe we can just change the copy to say something like,

> You have successfully activated your account. [Click here](http://floodlightproject.org/en/accounts/login/) to log in.

**Comment by ghing** [comment]
I'll need to take a look at the code to see what other scenarios trigger the warning message. We could also add logging to try to collect more information about how often users are hitting this.

I think it's a good idea to have two separate error messages, one for a general, unexpected activation error and one for the case where the user has already activated their account.  I'll have to look at the code for this to see how complicated that would be.

Also, I want to address this along with #786 as we should base our registration backend customizations off the latest stable release of the django-registration library.

Please add this to the Critical Bugs milestone if this should be addressed before I continue with the widgets.

**Comment by jwirfs-brock** [comment]
Totally agree that having two separate messages would be ideal, if that's doable.

**Comment by ghing** [comment]
@jwirfs-brock I took a look at the registration code and it would take a major reworking of the registration code to be able to differentiate between the case where a user enters an invalid activation code and where the user has simply clicked on the link more than once.  I suggest just updating the message to suggest to users that they may have already completed the activation.  We use similar copy for invalid password reset codes:

> The password reset link was invalid, possibly because it has already been used.  Please request a new 
> password reset

Can you provide me with the copy you'd like?  For reference, the existing copy is:

```
<h1><span>{% trans "There was a problem with your activation" %}</span></h1>
<p>{% trans "There was a problem activating your new account.  Please check that you correctly copied and pasted the activation link from your e-mail, or if you clicked on the link, try copying and pasting it.  If you're still not able to activate your account, please contact" %} <a href="mailto:{{ storybase_contact_email }}">{{storybase_contact_email}}</a>.</p>
```

To answer your earlier question about running into cases where activation would have failed, the case that I would anticipate would be if the user's email client mangles the link (because it's long, in order to make the activation codes unique). So, I think our message should reflect both the potential error and possibly a successful, but repeated activation.

**Comment by jwirfs-brock** [comment]
@ghing Ok, here's new copy, as code (I think I formatted it correctly...) and as text. Does this seem to cover our bases? Any suggestions on the copy?

```
<h1><span>{% trans "Oops, something unexpected happened with your account activation." %}</span></h1>
<p>{% trans "Either you clicked on the activation link more than once, or there's an error with the link." %}</p>
<p>{% trans "First, try <a href="http://floodlightproject.org/en/accounts/login/">logging in here</a> with your email address and password." %}</p>
<p>{% trans "If that doesn't work, try copying and pasting the activation link from your email into a web browser." %}</p>
<p>{% trans "Still stuck? Email us at  <a href="mailto:{{ storybase_contact_email }}">{{storybase_contact_email}}</a> and we'll get you sorted out." %}</p>
```

**Oops, something unexpected happened with your account activation.**

Either you clicked on the activation link more than once, or there's an error with the link.

First, try [logging in here](http://floodlightproject.org/en/accounts/login/) with your email address and password.

If that doesn't work, try copying and pasting the activation link from your email into a web browser.

Still stuck? Email us at  <a href="mailto:{{ storybase_contact_email }}">{{storybase_contact_email}}</a> and we'll get you sorted out.

**Comment by ghing** [comment]
@jwirfs-brock, I updated the copy again by adding a shorter top-level header, more comprehensively describing the likely causes of the problem, and making them a bulleted list for clarity. You can see the result in the screenshot below:

![screenshot from 2013-08-15 15 35 51](https://f.cloud.github.com/assets/110420/971593/651eb5ce-05ea-11e3-9ae8-04d6d9a3046a.png)

**Comment by jwirfs-brock** [comment]
@ghing I think the copy still needs a bit of work.

I don't like the "Account activation failed" header, because in every case I've heard reported from a user, the activation _didn't_ fail -- their account _has_ been activated. They just aren't getting directed to the log in page. Saying, "Account activation failed" immediately sends them a message that Floodlight is broken/not working. Or, they feel like they are doing something wrong. We don't want either of those to be their first experience with Floodlight. 

I also feel like the longer, more detailed explanation -- while very clear -- is information the user doesn't really need. They need to a) try to log in (they generally don't care that it's because they clicked the link twice -- also, telling them they already did something wrong isn't the best way to start the relationship), b) enter in the right link (I still haven't heard a case of someone using the wrong link), or c) contact us.

Thinking about this more, maybe instead of directing them to this page if they click the activation link twice or if they get a bad link because their email client garbled it, we should just direct them straight to the log in page (because in every case we've encountered so far, this is all they need to do). Then, if that log in fails, that's the proper time to direct them to this error page. Does that make sense?

**Comment by ghing** [comment]
@jwirfs-brock, I agree that the word "failed" is problematic, let's try to think of something a little less scary. What about this copy that puts actions to take first and explanations second.

# Account Activation

## Oops, something unexpected happened with your account activation

Try these steps:
- Try logging in with your email address and password. You may have already activated your account.
- Try copying and pasting the activation link from the email.
- Email us at help@floodlightproject.org and we'll get you sorted out.

> Thinking about this more, maybe instead of directing them to this page if they click the activation link twice or if they get a bad link because their email client garbled it, we should just direct them straight to the log in page (because in every case we've encountered so far, this is all they need to do). Then, if that log in fails, that's the proper time to direct them to this error page. Does that make sense?

Directing them directly to the login page when there's a problem with the activation and then redirecting them to an activation failure page on login failure adds a lot of complexity and probably involves altering some of Django's default login logic.  I'm reluctant to do this because the Django authentication modules are well tested and security audited by lots of people.  I think we can address this issue just as well in a couple of other ways.

As I was testing the activation flow out, I think one of the problems is that we never explicitly tell people that the account activation has succeeded, we just redirect them to the my accounts page (which, by default is pretty bare because they don't have any stories yet). So, they don't remember that they've already activated their account. 
1. Instead of redirecting the user directly to the "My Stories" page, we show them a "Your account has been activated" page and a link to the "My Stories" page.
2. We can redirect the user to the "My Stories" page, but show a message at the top of the page that says "Your account has been activated"
3. We can show them a "Your account has been activated" page with a link to the login page and ask them to log in.  That way they are explicitly informed that their account has been activated and have to think about the username/password they chose. 
4. We can redirect the user to the login page and show a message at the top of the page that says "Your account has been activated"

I'll also investigate adding some logging so we can have a sense of how often users revisit the activation page vs. visit an incorrect activation page.

**Comment by ghing** [comment]
Chatted with @jwirfs-brock and we decided on this solution:

> 1) we'll keep the activation error page with the new copy, for people who have a garbled link or click on the link twice
> 2) for activation that happens successfully, the users will be directed to the login page
> with a message at the top that says, "Your activation was successful. Log in below" or something like that
