### ISSUE TITLE
Storify embed lacks auto-size dimensions for story viewer

### ISSUE THREAD

**Issue by wendynorris** [denverfoundation/storybase#838]
The Storify-generated script embed does not indicate height or width dimensions. 

```
<script src="//storify.com/FloodlightStory/near-northeast-denver-story-raising.js"></script><noscript>[<a href="//storify.com/FloodlightStory/near-northeast-denver-story-raising" target="_blank">View the story "Near Northeast Denver Story-Raising" on Storify</a>]</noscript> 
```

When the script initially loads in the story viewer as a _modal window_, the embedded widget momentarily sizes correctly but then suddenly adjusts to a very narrow and not so-readable width. 

Same behavior occurs when story is viewed in its _own browser tab_ too.  

See example: http://floodlightproject.org/en/stories/story/

**Comment by wendynorris** [comment]
Came across this post which seems to point to creating custom CSS for Storify to control size and other style issues. 

http://jeffsonderman.com/2011/01/how-to-customize-the-appearance-of-storify-on-your-site/

**Comment by patternleaf** [comment]
Got some CSS from Wendy for this—assigning to myself.

**Comment by patternleaf** [comment]
@tekhneco This is going to take a bit more work than just adding CSS to our stylesheets. Perhaps storify widgets were implemented differently before but I don't think the solution on the link you posted will work with the current implementation. Currently storify embeds are iframed documents. Parent document CSS won't apply to the contents of an child iframe document, and also CSS is subject to the same-origin policy so it's even harder to apply styles to a document from another domain—in this case, storify.com. (Also, the current widget doesn't seem to have any of the ids mentioned in that article.)

What you're seeing when the widget loads is a result of how our current asset sandboxing works: it tries to figure out the rendered width of the content of the Storify embed and then sizes (our) iframe holding it. I'm not sure why it decides that it wants to be rendered at 300px because, yeah: it initially renders at a larger width.

What we were talking about doing before is to identify a bunch of widgets we want to support and hard-code styles/behavior for those widgets. I don't think this'll be too hard but it won't be as quick as adding some CSS. :(

That said, because the storify iframe seems to be wrapped in a div with a `sfy-story` class, we _can_ target that div inside our own asset sandbox iframe. This suggests a vector for a real solution when we get to it. In the meantime I can paste your CSS into our asset view. This is ugly and should be temporary but it will resolve this issue.

---

So, uh, **to summarize**: I have an ugly fix for this. A better fix will require a little more work. **Is the storify widget high-priority enough to justify an ugly temp fix?**

---

\cc @ghing

**Comment by wendynorris** [comment]
Well ... rats. Was hoping this would be easier.

Let's go with the ugly fix until we can devote the time to a longer term,
broader widget behavior solution. There are some publishing projects that
are on hold until the Storify width embed is resolved, even temporarily.

How much time will this take to implement?

**
_wendy norris http://about.me/wendynorris_
ceo + founder :: tekhne media, inc
a digital information and media collective
720 281 9378 :: mobile

*\* http://about.me/wendynorris
*
*

**Comment by ghing** [comment]
@patternleaf I'd like to see your quick and dirty fix and then see if there's a way we can standardize the way we detect certain types of embeds and apply workarounds.  That seems like a middle ground between reworking the embed rendering to cover all cases and haphazardly injecting workarounds.

**Comment by patternleaf** [comment]
@ghing Simple fix is to include style rules targeting the embed in the asset content view—asset_content.html. That's the view that is found at /assets/&lt;id>/content and is loaded as the src in our sandbox iframes. For this—the quick and dirty version—it's just a style that happens to match the embed container:

asset_content.html:

``` html
<!doctype html>
<html>
    <head>
        <style>
        ...
        .sfy-story {
            width: 600px;
        }
        ...
        </style>
    </head>
    <body class="asset-content">
        {{ asset.body|safe }}
    </body>
</html>
```

This works because the storify embed comes wrapped in a `.sfy-story` container. Let me know if I'm not explaining the simple fix sufficiently.

One idea I had for a more developed approach might detect the kind of embed and put some classes on the body of the sandboxed asset view (alongside `asset-content`), with which we could target different asset content in a stylesheet. I wonder if there may be embeds where we need some custom javascript in addition to CSS.

**Comment by ghing** [comment]
@patternleaf Can you test your approach and if it works, we can figure out a way to generalize it?

Off the top of my head, I'd say the solution might be to add embed type detection to the HtmlAsset model class and then add methods that dynamically add CSS/JavaScript (either inline or through a link) to the view context.  Maybe the way to do this would be through template tags that have a signature like this:

```
{% embed_fix_styles asset %}

...

{% embed_fix_scripts  asset %}
```

The template tags would call the type detection method on the asset and render a template based on the type (e.g. embed_fix_styles_storify.html, embed_fix_scripts_storify.html).  The template tags would return an empty string for unmatched asset types.

**Comment by patternleaf** [comment]
@ghing That would be fine, though at least for style-based fixups I kind of feel like it's semantically nicer to have a single stylesheet with all known fixes and then render an extra class on the body of the content view to select the right fixes. So in the view we'd have:

``` html
<body class="asset-content {% asset_content_classes asset %}">
```

For a storify embed this would render to, say:

``` html
<body class="asset-content foreign-embed storify">
```

and in the fixup stylesheet:

``` css
body.foreign-embed.storify {
  width:600px;
}
```

Also we wouldn't have to make a new template file for every embed type. We could do something similar for javascript too: ie, have a single file with something like

``` javascript
$(document).ready(function() {
// ...
  $('body.storify').find('...').doSomething();
// ...
  $('body.other-embed').find('...').doSomethingElse();
// ...
});
```

Let me know what you think ...

**Comment by ghing** [comment]
@patternleaf, I'm definitely on-board for assigning a class name for each embed.  Let's make sure it has a clear namespace, e.g. `storybase-embed-storify` as assigning body classes often makes it confusing as to which piece of code is creating the classes.

As for monolithic fix stylesheets and JavaScript, I think that's fine, but we should just try to make the files really cleanly organized and documented.

For what it's worth, my idea of separate css/javascript for each fix is based on the pattern that Modernizr/YepNope uses.

**Comment by patternleaf** [comment]
> For what it's worth, my idea of separate css/javascript for each fix is based on the pattern that Modernizr/YepNope uses.

Ah, I see. I usually just err on the side of monolithic files since they can be downloaded once and cached client-side.

OK, well as a short-term/half-way measure, to close this issue quickly, how about this:
1. Add link to {{ STATIC_URL }}css/foreign-embeds.css in asset_content.html
2. Put the storify fix in foreign-embeds.css.
3. Open a new issue for implementing the rest.

Open to other names for the css—storybase-embeds.css?—"foreign" is just what I thought of first. Also I guess it would be nice to be able to use LESS for the fix stylesheet, but I'm not sure it's worth the trouble to wire up a new LESS compile target ... another option would be to just put our fixes into our main stylesheet, which would already have been downloaded. Do you have any thoughts on that?

**Comment by ghing** [comment]
That strategy sounds fine. Just be sure to document the stylesheet file abundantly and include TODO: comments describing the path to a more robust solution.

For naming the file, `foreign-embeds.css` is fine. I also like `foreign-embed-fix.css`

We should definitely use LESS for this.

In this case, I think it's fine to include it in the main stylesheet (but via a LESS include) since they're loading that anyway.

**Comment by mgrayinnovation** [comment]
Moved to index of issues for reference during Pivot: https://docs.google.com/document/d/1dmlOEQJwYx0MddonRLmtN_zAitJ-lJyPm5W272nl6U8/edit
