### ISSUE TITLE
Improve user experience around editing/syncing sections and section collections.

### ISSUE THREAD

**Issue by patternleaf** [denverfoundation/storybase#842]
While editing builder sections, it can take a while for server-client sync to settle down. Particularly when moving sections around, it looks like there's an http request sent for every section. In a story with several sections and following a few moves, this can add up to quite a bit—as much as 10 seconds or so. Additional edits during that time can be temporarily reverted as earlier states are synched back before the most recent moves/edits have a chance to make the round-trip. Also during this time, the section bar is typically in an inconsistent state wrt "Add a Section" buttons.

I haven't been able to cause any case of _major_ inconsistency that wasn't eventually resolved once I let everything settle (but see #843)—I assume Backbone guarantees model consistency for us across non-deterministic request/response timing?—but if I didn't know what was going on, I might nonetheless be frustrated at:
1. Being able to make edits which apparently take instantly
2. Having those edits reverted temporarily, and/or seeing visible artifacts of incomplete sync (section bar not drawing "correctly" during sync)
3. Having to wait without a clear indication of when everything is "baked"

My suggestion is to:
- At least provide a "working" indicator that indicates _something_ is happening whenever any model is syncing. The Save button state isn't clear to me, and doesn't seem to match up with when the last round-trip request has completed when several are outstanding.
- Maybe investigate how to restrict editing on sections or section collections that are not fully synced yet.

I'm not sure if our use of Backbone can be modified to consolidate some of this synchronization, or do it less frequently.

Another alternative might be to use local storage for model-to-datastore syncs (instant), and then periodically run a single consolidated request to update the server. Not sure of best practices here. This is probably one for builder v2.

**Comment by ghing** [comment]
@patternleaf, I think that I wrote a lot of the views to be overly pessimistic.  That is, they update when the model syncs (i.e. gets a response from the server) rather than when the user updates the model. This is definitely something that we should clean up, maybe after we finish with the widget stuff.  I feel like the UI should trust the local state and just inform the user when the changes can't be saved.  Similarly, the app saves a lot, and I'm not sure it's neccesary to commit changes on every UI interaction. It might make more seynse to add "dirty"  to a set and save everything in that set every X minutes or seconds.

The many requests for reordering sections is a known design issue.  I couldn't think of good RESTful semantics for updating all the weights (which control the ordering) of the sections in one request.  This is definitely something we can figure out, I just haven't had time to do it.

**Comment by patternleaf** [comment]
@ghing Understood. I think it makes a lot of sense to slave view state to server state—that's probably how I would do it initially, too. The more I think about it, the more it seems to me like a cache hierarchy-like scheme might give us the best of all worlds: in-memory model, fine-grained local storage saves for recovery in case of error (could also allow for using builder while offline?), and periodic snapshots synced to server. Anyway we can talk more when we get around to this.

**Comment by mgrayinnovation** [comment]
Definitely worth reviewing as we move to P4, though this might be moved to P7 for later organizing.

**Comment by mgrayinnovation** [comment]
Also, see closed issue #843 for additional insight and info from previous team.
