### ISSUE TITLE
Unsaved asset data lost when asset view is re-rendered

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#847]
Here's the workflow:
1. In a side-by-side layout, I added a text asset on the left container.
2. I typed in some text, but didn't hit save.
3. On the right container, I also added a text asset.
4. I typed in some text and _did_ hit save.
5. When I did, I first see this in the left container:
![screen shot 2013-08-21 at 8 27 18 am](https://f.cloud.github.com/assets/1020518/1002096/fbf134e6-0a76-11e3-849b-e3dfcdba5016.png)
6. And then I see this when I click "Save":
![screen shot 2013-08-21 at 8 28 57 am](https://f.cloud.github.com/assets/1020518/1002073/99313e00-0a76-11e3-9296-4a77cd7587eb.png)
7. I had to click "Cancel," thus losing my text.
This seemed to happen regardless of what type of asset I added in the right container (i.e., I tried it with adding and image, and observed the same thing).

I also noticed some strange behavior when creating a new section when I had un-saved text. I'm including this here just in case it's related and will help you figure out what is happening. Here's the workflow:
1. In an empty section, I created a text asset.
2. I typed in some text but didn't hit save.
3. I clicked "Add Section"

Scenario 1...
4a. In the new section, I just looked at it, but didn't edit at all (did not add any assets)
5a. I navigated back to the original section. I saw the UPPER screen shot from above.
6a. When I clicked "Save" the text was rendered correctly.

Scenario 2...
4b. In the new section, I added an image asset. I didn't edit it, but just hit cancel.
5b. I navigated back to the original section and saw the LOWER screen shot from above.
6b. I couldn't save the text, and had to hit "Cancel," thus losing it.

I know this is kind of confusing, so I can do a video screen capture if that would be easier.

One solution may just be to have text assets auto-save in the same way the summary and call to action do. @ghing Could you remind me again why we don't do this? I believe it had to do with the way assets are created and saved?

**Comment by ghing** [comment]
@jwirfs-brock I think we can actually do auto-save of text assets. It wasn't implemented in the first place because, to me, it doesn't make sense for other asset types and the asset creation/editing was made to standardize across the asset types. I do feel like having auto save for text assets makes sense.  If you'd like this, can you open the request as a separate issue since the issues you're describing above reflect bugs in how the editor is generated and not just a lack of auto-save.

**Comment by ghing** [comment]
Updated title from "Unsaved text in text asset gets lost when user creates a new asset, saves" to "Unsaved asset data lost when asset view is re-rendered" to better reflect the root cause of this issue.

**Comment by ghing** [comment]
The underlying cause of this issue is due to the behavior of `SectionEditView`.  When a section's `assets` collection syncs, the view's `renderAssetViews()` method is called and the asset edit view's `render()` method is called.

Inside `SectionAssetEditView.render()`, the rich text editor is reinitialized, which is likely what causes the editor to disappear.

I believe the solution is to track when the asset is in the process of being edited and short circuit the rendering if this is the case.

While we keep track of the view's state, we can't use that here because we can't differentiate between the the case where the view is in the edit state and re-rendered and when the view is switching to the edit state and being rendered at the first time.

**Comment by ghing** [comment]
Also, we could just not have `SectionEditView` re-render all its sub-views when the `assets` collection syncs and instead only have the changed subview re-render.  I need to figure out the reason for doing that in the first place.
