### ISSUE TITLE
Story viewer should link back to story detail page and Floodlight

### ISSUE THREAD

**Issue by ghing** [denverfoundation/storybase#851]
This is motivated by a discussion of the link targets for stories in the embed widget (#741) started by @jwirfs-brock with [this comment](https://github.com/PitonFoundation/atlas/issues/741#issuecomment-23433937)

The story viewer should have a link back to the Floodlight homepage and to the story's story detail page.

One potential gotcha is determining whether the viewer is opened in a modal popup or in its own window/tab and opening the link accordingly.

**Comment by ghing** [comment]
Assigned to @bpawlak for wireframing.

**Comment by bpawlak** [comment]
Initial thoughts:

I think it's best to put the logo in the footer.  In doing so I think we should also reduce the vertical height of the footer.  (it's kind of tall right now).  That means:

a) moving page indicator "(1/3)" between the prev and next buttons
b) removing share button (it's on the story detail page as a button, in the viewer it can be an icon in upper-right)
c) using a different icon for view in new tab (right now we're using font-awesome's icon-share, so that should prob. be the share icon.  I suggest "icon-desktop"
d) tooltips for all top icons
e) placing the logo in the bottom right.

![viewer](https://f.cloud.github.com/assets/2250519/1058784/eff24554-118d-11e3-9dd7-312f00ca86a4.png)

**Comment by ghing** [comment]
@bpawlak makes sense to me.  What about the link to the story detail page?

**Comment by ghing** [comment]
Re link to story detail page, this came up in a chat today with @patternleaf:

> Eric:  random aside, looking at bill's mock-up of the viewer. i wonder if we put some of the detail view's  info/imagery on the first page along with the fully summary, it would make that experience nicer. it's just this mostly-blank page. it looks like something didn't load...
> me:  yeah. I really don't like the summary pushed to the top of the box
> and it would be nice to show the featured image too
> Eric:  yeah
> me:  and then you could link to the detail page somewhere from the summary slide

**Comment by bpawlak** [comment]
That makes sense to me.   I mean, "yeah"       :)

**Comment by jwirfs-brock** [comment]
+1 to Eric's comment about the summary page. I've had several people
mention this as an aesthetic thing they'd like to change.

**Comment by ghing** [comment]
Assigning to @patternleaf for wireframing/sketching better "Summary" display

**Comment by jwirfs-brock** [comment]
One thought for @patternleaf  on tge Summary page is maybe we could expose
the table of contents on the summary page.

It's valuable info, but not really being used as-is.

**Comment by jwirfs-brock** [comment]
Oops, sorry for typos and incoherence on that comment :p I'm on my mobile.
I'll try to send over some sketches once I'm back at my laptop.

**Comment by jwirfs-brock** [comment]
So, some things to potentially include on the "Summary" view:
- table of contest/list of story's sections
- featured image _yes?/no?_ (It look really nice on the story detail page, but I am not sure if we want it here or not -- especially if the featured image is coming from elsewhere in the story.)
- associated projects and organizations

It doesn't really make sense to have topics and tags, because to me those seem more like meta-data that help someone decide whether or not they want to read the story. They seem less relevant once a reader has already started reading.

One thing to think about is that, even with our notification for long summaries, we still have some stories with crazy-long summaries. Here's one example: http://floodlightproject.org/stories/americorps-attendance/ Whatever extra information we add, we have to make sure that the full-text for these long summaries still fits nicely.

**Comment by bpawlak** [comment]
We've talked about including the TOC a number of times... I think that makes the most sense to add.  I included the featured image (below) but it's huge.  We might want to scale things a bit.

![toc](https://f.cloud.github.com/assets/2250519/1061027/75df5fac-11c1-11e3-91bc-700a1e42ba22.png)

**Comment by jwirfs-brock** [comment]
@bpawlak Hmm, I do this like the two-column layout. It looks nice, especially given that the majority of sections are side-by-side. 

But we'll still have the problem of not being able to fit all of the text, even if we scale down the image. (Which is, I suppose, our own fault for not making the summary character-limit a hard limit ;P) Any other ideas?

**Comment by bpawlak** [comment]
I think we'll always have the potential problem of not being able to fit all of the text (throughout the rest of the story), if an author is really adept at verbosity, won't we?

**Comment by bpawlak** [comment]
Page 4 of that story already scrolls...

**Comment by jwirfs-brock** [comment]
True, and maybe we should be designing for the average summary length, not
the longest.

@ghing I know you've pulled some data on summary length for us in the past.
Any chance we could get an updated version?

**Comment by jwirfs-brock** [comment]
@bpawlak Agree that scrolling is unavoidable. But I still think we should
do our best to minimize it.

**Comment by ghing** [comment]
As of 2013-08-31, here's the averages for Story fields:

Average title length: 45
Average summary length: 428
Average summary words: 66

**Comment by jwirfs-brock** [comment]
Thanks, Geoff. Yeah, the example I shared to show what a long summary looks
like is definitely an outlier:

Its summary length is 356 words, 1975 characters.

Let's design for the average length, but make sure that you can still read
the longer ones via scrolling.

**Comment by jwirfs-brock** [comment]
Note that this issue was originally opened with the intention of providing a way to get back to the story detail page. In the current version, it still doesn't have that link, right? Or am I just missing it...

This is important because with the widget stories open in the viewer in a new tab or window, so there is no way to see the story detail page.

**Comment by ghing** [comment]
@jwirfs-brock, good catch. What microcopy would you recommend for this link, and is there any icon at http://fortawesome.github.io/Font-Awesome/icons/ that seems appropriate?

**Comment by jwirfs-brock** [comment]
How about "About this story"? I like the th-list icon:
http://fortawesome.github.io/Font-Awesome/icon/th-list/

**Comment by ghing** [comment]
@jwirfs-brock, how does this look to you?  The "About this story" link is in the upper-right-hand corner of the viewer next to "Share this story". 

![screenshot from 2013-09-25 17 12 26](https://f.cloud.github.com/assets/110420/1213745/9ec372b4-262f-11e3-851f-a9dbfd13ba79.png)

**Comment by jwirfs-brock** [comment]
This looks good!

**Comment by ghing** [comment]
@jwirfs-brock, I noticed that on my displays, the summary text was being pushed below the fold:

![story_viewer-summary_text_hidden](https://f.cloud.github.com/assets/110420/1219755/e608d974-26d0-11e3-8dd4-7919e7136849.png)

To me, the summary text is more important than the table of contents. It now looks like:

![viewer-summary_text_moved_up](https://f.cloud.github.com/assets/110420/1219756/e6104a4c-26d0-11e3-8c13-bc52ed78df58.png)

I also removed the byline as its redundant with the byline in the title bar.

If you have an objection to this, let me know, but I think it's better.

**Comment by jwirfs-brock** [comment]
@ghing I like these changes -- they definitely improve the readability.
Nice work.

If it would be useful, I can browse some more stories on dev to see if
everything looks presentable. Stories with super long summaries might still
look funky ... but as we discussed before, that is something we are trying
to discourage so it doesn't make a lot of sense to design around it.
