### ISSUE TITLE
Admin view for Stories - can't see publish/draft status in Chrome

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#890]
This is a very minor, yet potentially annoying thing I noticed.

When I am looking at the list of stories in the admin view (http://floodlightproject.org/admin/storybase_story/story/), I can see the full info about each story in Firefox. But in Chrome, the filter on the right overlaps with the story list, so I can't see the publish/draft status of the stories. There doesn't appear to be any way to scroll over.

This isn't a huge problem, because I can filter stories by publish/draft status. But I do often check in on the story list and glance at it in this view to get an idea of who is currently using Floodlight and whether there are any users who might potentially need help.

As far as I can tell, this happened after the Django 1.5 update was pushed.

View in Firefox (working properly):
![screen shot 2013-11-12 at 9 57 11 am](https://f.cloud.github.com/assets/1020518/1522671/3c7439a8-4bab-11e3-808c-6774e3241392.png)

View in Chrome (info is cut off):
![screen shot 2013-11-12 at 9 55 54 am](https://f.cloud.github.com/assets/1020518/1522672/412845de-4bab-11e3-91de-14f6b2dd8a82.png)

**Comment by ghing** [comment]
@jwirfs-brock, the issue you were seeing was because I created a test story with a title that had a really long, uninterrupoted "word" (actually something like "asdasdasdsadasdasd...") in the title.  The columns have CSS styles (which are Django's defaults) that specify `white-space: nowrap;` which cause the browser to display my really long "word" in the title on one line and push all the other columns over.  I just changed the title for the test story which fixed they layout, at least in my browser, Chrome 30.0.1599.114.

I don't imagine that we'll see actual titles with such long words in them.  Note that the issue is with the length of words in the title, not the title itself, as longer titles should wrap.
